// Drop into: content/prospect-briefs.ts
// Full corpus of 25 client + 2 investor pre-sales briefs synthesized from
// Notion GTM home / Pre-sales briefs. Each brief is the raw account-level
// intelligence that feeds the pipeline-map and voice-of-customer sections.

export type ProspectBrief = {
  account: string;
  contact: string;
  geography: string;
  industry: string;
  scale: string;
  status: 'Live' | 'Active' | 'Pilot scoping' | 'Stalled' | 'Lost' | 'Exploratory' | 'Pre-outreach' | 'Pre-outreach (warm)' | 'Channel partnership' | 'Investor';
  tier: 'Tier 1' | 'Tier 2' | 'Investor' | 'Channel';
  leadSource: string;
  erp: string;
  wedge: string;
  signalOrLearning: string;
  nextStep?: string;
};

export type ProspectBriefsData = {
  intro: string;
  briefs: ProspectBrief[];
  crossCuttingSignals: Array<{
    signal: string;
    evidence: string[];
    implication: string;
  }>;
  channelPartnerships: Array<{
    partner: string;
    nature: string;
    keyTerms: string;
    fitNote: string;
  }>;
  investorIntel: Array<{
    investor: string;
    fund: string;
    thesisFit: string;
    objectionsRaised: string[];
    actionItem: string;
  }>;
  pipelineDistribution: {
    byStatus: Array<{ status: string; count: number }>;
    byTier: Array<{ tier: string; count: number }>;
    byGeography: Array<{ geo: string; count: number }>;
    byIndustry: Array<{ industry: string; count: number }>;
    bySource: Array<{ source: string; count: number }>;
  };
};

export const prospectBriefsData: ProspectBriefsData = {
  intro: `**Account-level intelligence corpus** — 25 client + 2 investor pre-sales briefs synthesized from the Notion GTM Home / Pre-sales briefs. Each entry is the discovery-grade fact set behind a documented prospect: what they do, what hurts, what we'd pitch, and what we've learned. This is the raw signal that feeds the pipeline-map, the buyer-job-map, and the voice-of-customer cross-cutting analysis.`,

  briefs: [
    // ─── Live / Active deals ───
    {
      account: 'Zalora',
      contact: 'Shivam (CFO) + Francisco, Marie Claire, Azar, Aliaa, Frank, Sandeep',
      geography: 'SEA (HQ Singapore, ops MY+SG)',
      industry: 'Fashion e-commerce',
      scale: 'Mid-market enterprise',
      status: 'Live',
      tier: 'Tier 1',
      leadSource: 'Personal connection (Shivam)',
      erp: 'SAP + UiPath (40-50% deterministic auto)',
      wedge: 'P2P invoice processing (live) → expanding to O2C billing + cash app',
      signalOrLearning: 'Strict park-then-post SAP governance. "RPA complement" framing was the pitch that landed: we handle the 50% UiPath can\'t. Zalora is the canonical SEA reference customer.',
      nextStep: 'Lock O2C ship date Q3 2026. Public case study by Q4 2026.',
    },
    {
      account: 'Spectrum Brands',
      contact: 'Utpala Shelar (VP Controller) + Tammy McIntyre (Sr Dir AP) + Tom Brighton (Sr Dir AR)',
      geography: 'US ($2.8B NYSE-listed)',
      industry: 'CPG',
      scale: 'Mid-to-upper-mid enterprise',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'Warm intro via KPMG overlap',
      erp: 'SAP S/4HANA (year 5 of migration; IT fully constrained)',
      wedge: 'AP + AR + deductions + cash application bundle — exactly the bundle they couldn\'t get from HighRadius at $1.2-1.5M',
      signalOrLearning: '**The validation deal.** "AP, AR, deductions, cash app are open territory for outsourcing/automation." Quote: HighRadius rejected on price; couldn\'t justify the ROI.',
      nextStep: 'Schedule Tammy + Tom intros within 2-3 weeks. Demo with Spectrum\'s actual data shape.',
    },
    {
      account: 'Hindustan Coca-Cola Beverages (HCCB)',
      contact: 'Ashley D\'Souza (CDO — internal champion) + Harsh Bhutani (CFO) + Sunaina Dhanuka',
      geography: 'India (~$1.5B revenue; ~$10B IPO valuation)',
      industry: 'FMCG / beverages',
      scale: 'Enterprise',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'Warm intro via Ashley D\'Souza (friend offering to connect internally)',
      erp: 'SAP confirmed at system level (Coke One project)',
      wedge: 'AP / vendor invoice processing — 15 factories, 2,000+ distributors, 2M retail partners. IPO summer 2026 demands audit-grade controls.',
      signalOrLearning: 'IPO-driven finance ops upgrade window. 73% profit decline + 300 job cuts + new CEO = margin pressure. Refranchising created new intercompany flows. Use Ula FMCG background as credibility, not opener.',
      nextStep: 'Nipun reaches out to Ashley → connect to Harsh or Sunaina → diagnostic conversation, not pitch.',
    },
    {
      account: 'Apparel Group (Dubai)',
      contact: 'CFO Hiren Patadia',
      geography: 'GCC HQ + SEA ops',
      industry: 'Multi-brand apparel retail',
      scale: 'Enterprise mid-market',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'Evolv.ai referral',
      erp: 'TBD',
      wedge: 'AI in Finance — AP + AR scope',
      signalOrLearning: 'Hiren is narrative-led ("AI in Finance"). Lead with multi-product platform + agentic roadmap. FATOORAH e-invoicing in Saudi is the future regulatory hook.',
      nextStep: 'Confirm AP+AR scope. Quote within 30 days.',
    },
    {
      account: 'Inspire Brands',
      contact: 'Scott Cane (Sr Director, Accounting Shared Services & Finance Innovation)',
      geography: 'US ($32.5B system sales)',
      industry: 'QSR / multi-brand restaurant',
      scale: 'Enterprise — Roark Capital-owned',
      status: 'Pilot scoping',
      tier: 'Tier 1',
      leadSource: 'Cold research (perfect 10/10 ICP score)',
      erp: 'Oracle Cloud Suite (ERP/GL, FCCs, ARCs, EPBCs, EDM)',
      wedge: 'AP — currently hiring Global AP Director to manage 25 AP professionals',
      signalOrLearning: '**"I like your approach. SLAs, you own the process and the optimization. That makes sense to me."** Outcome-based pricing resonated. Requires SOC 1 Type 2 (not SOC 2) + audit firm name. Prefers "mirror-then-transform" — replicate workflows into AI scripts before transforming. Main pipeline locked to Oracle implementation through summer 2026; pilot must target secondary feeds or leakage problem.',
      nextStep: 'Nipun follow-up: pricing, references, SOC 1 audit firm. Second call with broader stakeholders + Prithvi.',
    },
    {
      account: 'Quince',
      contact: 'Krishnaprasad KR ("KP", Financial Controller, India GCC)',
      geography: 'US (SF) + India GCC',
      industry: 'M2C e-commerce',
      scale: '$1B+ revenue, $10.1B valuation, $500M Series E (March 2026)',
      status: 'Pre-outreach (warm)',
      tier: 'Tier 1',
      leadSource: 'TBD (Freshworks alumni / Stanford / Lightspeed network)',
      erp: 'Likely NetSuite or SAP — confirm in discovery',
      wedge: 'Supplier AP across 60+ factory partners (multi-currency, non-standard formats)',
      signalOrLearning: 'KP took Freshworks through NASDAQ close cycle. Knows audit, SOX, multi-entity close. "Building controllership at Quince during this growth phase is a different kind of challenge." Canada launch = international AP complexity. Zalora analog maps almost perfectly.',
      nextStep: 'Identify warm intro path. Confirm ERP. Draft outreach (warm + cold LinkedIn variants).',
    },
    {
      account: 'Hitachi Vantara',
      contact: 'Mathew Sia (Controller)',
      geography: 'SEA (HQ Singapore)',
      industry: 'Tech / data infrastructure',
      scale: 'SEA enterprise',
      status: 'Stalled',
      tier: 'Tier 1',
      leadSource: 'SSON Singapore event',
      erp: 'SAP',
      wedge: 'AP + AR (specifically wanted cash application — which we did not have at Nov 2025)',
      signalOrLearning: '**The lesson.** Quote: "More interested in cash application, which we did not have." They wanted the bundle, we showed up AP-only. Walked. Validated Signal 1 — AP-only loses, the bundle wins.',
      nextStep: 'Q3 2026 — once O2C cash app is live, re-approach with the updated bundle and Spectrum reference.',
    },

    // ─── SEA pipeline ───
    {
      account: 'JLand Group (JLG)',
      contact: 'Syahir (Process Transformation), Azua, Y. Kong',
      geography: 'Malaysia',
      industry: 'Conglomerate / construction',
      scale: 'Mid-market enterprise',
      status: 'Exploratory',
      tier: 'Tier 1',
      leadSource: 'SSON Singapore event',
      erp: 'Microsoft Dynamics',
      wedge: 'TBD — Process Transformation team contact, not Finance. MyInvois mandate makes timing strategic.',
      signalOrLearning: 'NDA stretched 1+ month. Right pattern, wrong contact. Workshop-before-POC fits their decision style. MyInvois compliance is the wedge.',
      nextStep: 'Direct ask for Finance head intro. If not gettable in 30 days, deprioritize.',
    },
    {
      account: 'Agro Corp',
      contact: 'CFO + Group Controller',
      geography: 'Singapore',
      industry: 'Mid-market',
      scale: 'Mid-market enterprise',
      status: 'Exploratory',
      tier: 'Tier 1',
      leadSource: 'Personal network (Nipun)',
      erp: 'TBD',
      wedge: 'Partnership / multi-product',
      signalOrLearning: 'Singapore deal — PSG / Peakflo is the structural competitive frame. Without PSG approval, structural pricing disadvantage. Frame as platform partnership (R2R + multi-product expansion path) — the angle Peakflo cannot match.',
      nextStep: 'Hold for 90 days while PSG application is in motion.',
    },
    {
      account: 'Welspun',
      contact: 'Sudeep Shrivastava + Akhilesh (Architecture Lead — technical gatekeeper)',
      geography: 'India conglomerate',
      industry: 'Multi-vertical (textiles, infrastructure)',
      scale: 'Conglomerate',
      status: 'Stalled',
      tier: 'Tier 1',
      leadSource: 'SSON Singapore event',
      erp: 'Multiple (not specified). Internal AI tools cover ~20%.',
      wedge: 'P2P (likely VIM-replacement frame) + on-prem hard requirement',
      signalOrLearning: '**On-prem is a hard requirement.** Sudeep wanted both PaaS + use-case-as-a-service pricing with explicit tiers. POC with 50-70% improvement threshold defined upfront. NDA-stretching pattern — likely shopping multiple vendors. Indian per-transaction commodity pressure makes commercials fragile.',
      nextStep: 'Single check-in to confirm dead, then deprioritize.',
    },
    {
      account: 'Coca-Cola',
      contact: 'TBD (warm intro path)',
      geography: 'Global',
      industry: 'FMCG',
      scale: 'Enterprise',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'Internal warm intro',
      erp: 'SAP',
      wedge: 'P2P with explicit 11-dimension VIM head-to-head: extraction, first-pass automation, learning, tax/GL coding, email ingestion, customization, implementation/upgrade, expertise, country compliance, fraud detection, AR.',
      signalOrLearning: '**This is the VIM-displacement archetype.** The 11 dimensions are the battlecard structure for every SAP-shop deal we run.',
      nextStep: 'Build the 11-dimension VIM battlecard within 30 days.',
    },
    {
      account: 'Flipkart',
      contact: 'Shreya, Saurav, Srikanth + Nishit (close-out)',
      geography: 'India',
      industry: 'E-commerce / ads',
      scale: '$30B+ revenue',
      status: 'Lost',
      tier: 'Tier 1',
      leadSource: 'Warm intro (Shreya)',
      erp: 'Oracle Fusion',
      wedge: 'P2P — RO automation (50-60 RO templates, poor quality scans)',
      signalOrLearning: '**Lost to Uttara at ₹15/RO.** Cogniquest at ₹1.6/invoice, Nanonets at ₹4 confirm Indian enterprise sub-$5 commodity dynamic. **Lesson, not opportunity.** Validates Signal 2 (India enterprise priced itself out).',
      nextStep: 'No action. Possible future analytics dashboard opening but not priority.',
    },
    {
      account: 'Boomerang Catapult / Rehmann CPA',
      contact: 'Warner Queeny (Principal, ex-Dunzo Founding Partner)',
      geography: 'US Midwest (Michigan)',
      industry: 'CPA channel partner',
      scale: 'Channel test',
      status: 'Channel partnership',
      tier: 'Channel',
      leadSource: 'Personal network',
      erp: 'N/A',
      wedge: '80/20 revenue share model with mid-market CPAs',
      signalOrLearning: '**"Cold outreach is nearly dead. CFOs are drowning in AI pitches. Need boots-on-ground with personal relationship-based selling — lunches, warm intros."** Validation of US warm-channel motion. 6-month learning agenda.',
      nextStep: 'Track customers sourced, deal velocity, ACV, margin after rev share.',
    },

    // ─── New from Notion (not previously in pipeline-map) ───
    {
      account: 'Yoco',
      contact: 'Bradley Wattrus (Co-CEO ops/finance/governance) + Carl Wazen (CBO)',
      geography: 'South Africa + Netherlands',
      industry: 'Fintech (SME payments + commerce)',
      scale: '$2B+ TPV; ~$60-80M revenue est; ~330 employees',
      status: 'Pre-outreach',
      tier: 'Tier 1',
      leadSource: 'Cold research',
      erp: 'Likely cloud-native; Zendesk/Freshdesk for support (TBC)',
      wedge: 'Dual pilot — customer support (one channel) + transaction reconciliation across SA + NL',
      signalOrLearning: '200K+ merchants on ~330 employees. Leadership transition Sep 2025 (founder Katlego replaced by Bradley + Lungisa). Series C $107M+ from Dragoneer. SARB clearing designation March 2025 increases compliance burden. G2 reviews show support quality degradation.',
      nextStep: 'Cold outreach to Bradley with operational scaling angle.',
    },
    {
      account: 'Verto',
      contact: 'Ola Oyetayo (Co-Founder & CEO)',
      geography: 'UK HQ + Lagos, Nairobi, Cape Town, Dubai, NYC, Pune, Malta',
      industry: 'Cross-border B2B payments / FX',
      scale: '$25B+ payment volume; ~47 employees; 6+ legal entities',
      status: 'Pre-outreach',
      tier: 'Tier 2',
      leadSource: 'Cold research',
      erp: 'Unknown (likely Xero/QuickBooks)',
      wedge: 'Multi-currency reconciliation across 49 currencies + multi-entity close across 6+ jurisdictions (UK FCA, UAE DFSA, Nigeria, Kenya, SA, Malta)',
      signalOrLearning: '$25B volume on ~47 people = exactly the complexity-to-headcount ratio we win at. US-Africa corridor launch April 2026 + Atlas API embedded finance compounds. Compliance ~5% of revenue for regulated fintechs.',
      nextStep: 'Cold outreach to Ola with Yarken-style framing.',
    },
    {
      account: 'Grab (GrabFin)',
      contact: 'Charlie Tong (Head of Commercial, GFin & Portfolio Strategy)',
      geography: 'SEA (HQ Singapore)',
      industry: 'Superapp / fintech',
      scale: '$3.37B revenue 2025, NASDAQ:GRAB',
      status: 'Pre-outreach',
      tier: 'Tier 2',
      leadSource: 'Cold research',
      erp: 'SAP confirmed (finance careers page)',
      wedge: 'GrabFin commercial ops — merchant settlement reconciliation OR lending ops documentation. Loan book scaling $1.3B → $2B by end 2026.',
      signalOrLearning: 'Charlie commercially-oriented (not direct ops budget owner). NTU alum. GrabX 2026 launched 13 AI features April 8. Anthony Tan: "Humans who don\'t use AI will likely be displaced." Charlie may be champion/connector; real budget owner is finance/ops leadership (Pauline Leow).',
      nextStep: 'Cold LinkedIn message referencing GrabX 2026. Long sales cycle — calibrate expectations.',
    },
    {
      account: 'Dafiti (Global Fashion Group)',
      contact: 'Fernando Casseb Lois (CFO — confirmed via Shivam intro)',
      geography: 'Brazil + Colombia',
      industry: 'Fashion e-commerce — Latin America',
      scale: '~€163M LATAM segment revenue',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'Warm intro from Shivam (CFO Zalora — sister company under GFG)',
      erp: 'TBD (likely SAP given GFG parent)',
      wedge: 'AP/AR finance operations — 3,000+ brand partners, marketplace seller payouts, multi-country tax (Brazil nota fiscal, ICMS, PIS/COFINS)',
      signalOrLearning: 'Fernando is **ex-Kraft Heinz ZBB / 3G Capital school** — performance-oriented CFO with cost-discipline DNA. Just brought in to tighten ops post-Argentina/Chile exits. Shivam: Fernando "keen to explore AI-led solutions to automate Finance." Active buyer intent.',
      nextStep: 'Reply to intro. Match Shivam\'s framing (AI for Finance, not outsourcing).',
    },
    {
      account: 'Changi Airport Group (CAG)',
      contact: 'Jacqueline Lee (SVP, CAG, Wharton classmate) → Yew Chee (Changi East contracts)',
      geography: 'Singapore',
      industry: 'Government infrastructure / aviation',
      scale: 'S$3.07B revenue FY24/25; S$10B+ T5 megaproject',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'Warm inbound — Wharton classmate',
      erp: 'Sesami eProcurement; DocuSign; DIVA Digital Factory with Accenture',
      wedge: 'Custom AI agentic workflows for contract claims recovery, variation order tracking, cost reconciliation across S$4.75B+ awarded contractor packages',
      signalOrLearning: '**Not standard finance ops.** Construction contract administration is the wedge. Government procurement = longer cycle (3-6 months). CAG is AI-forward (autonomous baggage tractors, digital twin) but construction contract ops likely lag passenger-facing innovation.',
      nextStep: 'Confirm Jacq\'s status (recent career break). Get Yew Chee\'s LinkedIn. Schedule Singapore trip.',
    },
    {
      account: 'iCar Asia / CARSOME',
      contact: 'Lu Shia (CFO iCar Asia) via Digbijoy (now at Zurich)',
      geography: 'Malaysia, Indonesia, Thailand, Singapore, Philippines',
      industry: 'Automotive marketplace',
      scale: '~$37.9M iCar Asia revenue; CARSOME Group profitable',
      status: 'Pre-outreach (warm)',
      tier: 'Tier 1',
      leadSource: 'Warm intro via Digbijoy (former CEO iCar Asia, known to Nipun)',
      erp: 'Custom CRM, GCP infra; no confirmed enterprise ERP',
      wedge: 'Dealer AP at scale — 13,000+ dealers across 5 countries; post-acquisition iCar Asia → CARSOME consolidation',
      signalOrLearning: 'Digbijoy ran iCar Asia 4 years — knows finance pain firsthand. **Double opportunity:** introduces to iCar Asia/CARSOME finance + own role at Zurich Insurance. Frame against captive team cost.',
      nextStep: 'Digbijoy connects to Lu Shia or CARSOME Group finance leadership.',
    },
    {
      account: 'Zurich Insurance Singapore',
      contact: 'Digbijoy Shukla (Head of Digital APAC, Apr 2026)',
      geography: 'Singapore (regional hub for APAC)',
      industry: 'Commercial insurance',
      scale: '$75.7B group revenue; 170+ employees Singapore',
      status: 'Pre-outreach (warm)',
      tier: 'Tier 1',
      leadSource: 'Warm intro via Digbijoy (known to Nipun)',
      erp: 'Microsoft Power Platform, Serrala FS2 (AP, NA only), HighRadius (AR), Azure OpenAI',
      wedge: 'Policyholder document processing for complex commercial risks — upstream of Zurich\'s underwriting AI investments (Program IQ, Edge Assist). Backup: broker commission reconciliation across 8 LoB + 40+ digital partners.',
      signalOrLearning: 'AI Lab (Singapore + Zurich + St. Gallen) focuses on underwriting/claims, not finance ops. Ericson Chan (Group CIDO, ex-Ping An) = builder mindset → position as managed services, not technology. Asia Insurance CFO Summit May 19-20 in Singapore = two-pronged approach with CFO.',
      nextStep: 'Schedule intro call. Lead with document processing pitch.',
    },
    {
      account: 'Sunday Insurance',
      contact: 'Cindy Kua (Co-Founder & CEO) + Benuel Ganesan (CFO)',
      geography: 'Thailand + Indonesia',
      industry: 'Insurtech (full-stack)',
      scale: '$106M raised; 1.6M+ customers; 100% YoY Thailand',
      status: 'Pre-outreach',
      tier: 'Tier 1',
      leadSource: 'Cold research',
      erp: 'Salesforce (Sales/Service Cloud, Tableau, Slack); proprietary AI/ML; Jolly™ superapp',
      wedge: 'Tier 1 customer support automation (claims/refunds/cancellations) — pre-empts Salesforce Agentforce evaluation',
      signalOrLearning: 'Already exploring Agentforce — validates the need. Position as: "Agentforce is a tool. We own the outcome." Multilingual support: Thai, Bahasa, English.',
      nextStep: 'Cold outreach to Cindy. 7-slide deck ready in Marketing Positioning folder.',
    },
    {
      account: 'EY India (Tax Technology)',
      contact: 'Venkatesh Narayan (Partner, National Leader Tax Technology) + Nitish Jain (AI Partner)',
      geography: 'India (Gurugram, Mumbai, Chennai, Pune, Delhi)',
      industry: 'Professional services / tax tech',
      scale: 'EY India ~$2.7B revenue',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'Cold + 8 mutual LinkedIn connections via Nitish (Naman, Ujjwal + 6 others)',
      erp: 'SAP BTP (DigiGST), proprietary India Tax Platform, EY GTA',
      wedge: '**Partnership / channel** — Neoflo as execution layer underneath EY\'s India Tax Platform + Tax and Finance Operate (TFO) managed services',
      signalOrLearning: 'Venkatesh post 4 months ago: **"With rapid adoption of AI agents, point solutions become less relevant as clients seek to automate processes end to end."** Direct alignment. Position as augmenting their capabilities, not competing with their platform. Risk: strong internal tech team building proprietary AI.',
      nextStep: 'Outreach via Nitish (warmest path). Frame as operational execution engine for TFO delivery.',
    },
    {
      account: 'Shyam Steel Industries',
      contact: 'Nikunj Beriwal & Team',
      geography: 'India',
      industry: 'Steel manufacturing',
      scale: 'Conglomerate group',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'TBD (cold or warm)',
      erp: 'SAP S/4HANA',
      wedge: 'Custom workflow design — multi-entity group structure across manufacturing, technology, distribution',
      signalOrLearning: 'Solution brief + proposed solution drafted. Customized workflow design.',
      nextStep: 'Send proposed solution / advance to next meeting.',
    },
    {
      account: 'Lula (Lulalend)',
      contact: 'Trevor Gosling (Co-Founder & CEO, ex-Goldman/KPMG) + Neil Welman (CTO)',
      geography: 'South Africa',
      industry: 'Fintech — SME lending + neobanking',
      scale: '$60M+ raised; ~100-200 employees; 70K+ applications processed',
      status: 'Pre-outreach (warm)',
      tier: 'Tier 2',
      leadSource: 'Warm intro via Ganesh',
      erp: 'Proprietary AI credit scoring; Access Bank infra',
      wedge: 'Customer support ops + loan operations reconciliation. Recent $21M from FMO + $10M from IFC.',
      signalOrLearning: 'AI-native culture — they use AI for credit scoring, not back-office. Trevor is ex-Goldman/KPMG = numbers-forward. Neoflo extends AI-first ops beyond credit scoring into back-office.',
      nextStep: 'Ganesh forwards intro email to Trevor.',
    },
    {
      account: 'Mitsubishi Corporation RtM International',
      contact: 'Vineet Kohli (CEO RtMI)',
      geography: 'Singapore HQ + Japan, US, India, 90+ countries',
      industry: 'Commodities trading (metals, minerals)',
      scale: '~$125M revenue; parent Mitsubishi Corp ~$150B',
      status: 'Pre-outreach',
      tier: 'Tier 2',
      leadSource: 'Cold research (Aakriti)',
      erp: 'Likely SAP given Mitsubishi parent; CTRM (Openlink/Brady/Aspect) for trade capture',
      wedge: 'AP automation — freight, warehousing, port charges. Provisional-to-final invoice reconciliation in metals trading.',
      signalOrLearning: 'Japanese trading houses prefer ecosystem-trusted vendors. Alternative entry: RtM Bharat (India) — newer entity, GST compliance complexity. Risk: finance may be centralized through MC parent.',
      nextStep: 'Identify Singapore CFO/Head of Finance via LinkedIn.',
    },
    {
      account: 'Oncourse Home Solutions',
      contact: 'Baqar Shameem (VP Tech Strategy & Delivery, Digital Transformation) + Dale Gerard (CFO)',
      geography: 'US (43 states)',
      industry: 'Home warranty / home repair',
      scale: '~$300M revenue; PE-owned by Apax (Dec 2021)',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'Cold research',
      erp: 'Microsoft Azure/SharePoint; Oracle (referenced in postings); MongoDB',
      wedge: 'AP automation for contractor/vendor invoice processing. ~3M customer contracts, claims dispatching, multi-brand multi-state.',
      signalOrLearning: 'Completed $1.66B WBS (whole business securitization, first-of-its-kind) — finance team under intense scrutiny from rating agencies. First-ever CTO hired Jan 2025. Baqar = transformation leader (BlackRock PMO, Six Sigma) — speak metrics.',
      nextStep: 'Schedule meeting with Baqar. Lead with WBS angle + Six Sigma metrics framing.',
    },
    {
      account: 'Angel One',
      contact: 'Ambarish Kenghe (AK, Group CEO) — re-entry via Vibs',
      geography: 'India (NSE: ANGELONE)',
      industry: 'Fintech / retail broking + 5 new verticals',
      scale: '35.7M clients; ₹5,172 Cr (~$620M) FY25 revenue',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'Prior relationship via Alltius (consolidated into Neoflo)',
      erp: 'Likely SAP/Oracle (TBC)',
      wedge: '**Finance ops, not customer support** — vendor AP and multi-entity reconciliation across 6 entities (broking + wealth + AMC + credit + insurance JV + GIFT City)',
      signalOrLearning: 'Angel One\'s SVP Engineering Shashank Kothari publicly: "Next phase of AI is the systems running underneath." That\'s our pitch, published by the prospect. AK\'s 40-45% EBITDA target = back office is the lever. **Do NOT sell support chatbot again** — Ask Angel is "in-house built" by AK\'s team. IITK alum bond Vibs ↔ AK.',
      nextStep: 'Vibs drafts 150-word note to AK. IITK + Ask Angel respect + finance ops wedge + 15 minutes.',
    },
    {
      account: 'Ionic Wealth (Angel One)',
      contact: 'Srikanth Subramanian (CEO) + Shobhit Mathur (CTO)',
      geography: 'India + Singapore + UAE',
      industry: 'Wealth management',
      scale: '₹10,083 Cr (~$1.2B) AUM; 1,900+ HNIs; 230+ team',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'Adjacent to Angel One re-entry',
      erp: 'Proprietary stack; 80% of codebase claims to be AI-generated',
      wedge: '**Different from Ionic\'s own AI** — Ionic built investor-facing AI (portfolio analysis, MF agent, financial planning). Neoflo brings what Ionic does NOT do: voice transcription, knowledge search, customer support automation, back-office process automation, workflow orchestration, audit trail compliance, on-prem deployment, multi-tenant.',
      signalOrLearning: '**Ionic is the proof wealth firms need AI; Neoflo is the product that gives it to them.** They built AI for their own business. Cannot be deployed at another firm. No back-office, no support, no compliance architecture.',
      nextStep: 'Likely separate from AK conversation. Could enter through Srikanth or Shobhit on the operations side.',
    },
    {
      account: 'Rimkus Consulting Group',
      contact: 'Vitali Edrenkine (CMO, Wharton 2010 — same cohort as Nipun)',
      geography: 'US HQ + 110+ offices, 5 continents',
      industry: 'Forensic engineering / consulting',
      scale: '~$296M revenue; 1,500+ people; PE-backed (HGGC, L Capital)',
      status: 'Pre-outreach (warm)',
      tier: 'Tier 1 — warm',
      leadSource: 'Wharton MBA classmate',
      erp: 'Likely fragmented per-entity (no public ERP signal)',
      wedge: 'Door via Vitali (marketing/sales ops AI) → real prize is F&A referral to CFO for post-15-acquisition multi-entity finance consolidation',
      signalOrLearning: 'New CEO Feb 2026 (Chris Rayasam, ex-Consor) = budget/vendor re-evaluation window. Vitali ex-DataRobot/Arcserve — knows AI hype-vs-substance. Rebrand from "Rimkus Consulting Group" to "Rimkus" = his work. **30-50% lower F&A cost across entities** mantra.',
      nextStep: 'Wharton coffee/Zoom catch-up — 80% him, 20% Neoflo.',
    },
    {
      account: 'Select Equity Group',
      contact: 'Bill O\'Boyle (Head of International Trading → moving under COO for AI restructuring; Wharton 2024-2026 cohort)',
      geography: 'US (NYC) + 3 continents',
      industry: 'Asset management ($30-35B AUM)',
      scale: '~200 employees',
      status: 'Active',
      tier: 'Tier 1',
      leadSource: 'Warm inbound — Bill initiated intro request via Serguei (Wharton)',
      erp: 'TBD (asset manager — likely SS&C/Advent or proprietary)',
      wedge: 'Finance ops (AP/AR) as entry → expansion path: month-end close → investor reporting → trade settlement reconciliation → compliance documentation',
      signalOrLearning: '**"We\'re actively outsourcing as part of our broader AI-driven restructuring."** As warm as inbound gets. COO-backed mandate. Don\'t lead with AI consulting — he wants someone to own the process. 360ONE is closest industry parallel.',
      nextStep: 'First call = discovery, not pitch. Tailored one-pager after.',
    },
    {
      account: 'Dossier',
      contact: 'Jodi Brauer (CFO, ex-PwC/Revlon/KIND/ZitSticka)',
      geography: 'US (NYC) + French manufacturing (Grasse)',
      industry: 'DTC beauty / fragrance',
      scale: '~$100M annualized; ~75-100 employees; profitable since 2022',
      status: 'Active — Proposal sent Apr 11, 2026',
      tier: 'Tier 1',
      leadSource: 'TBD',
      erp: 'QuickBooks (confirmed); Bill.com for AP approvals + payments. NetSuite planned for early 2027.',
      wedge: 'AP three-way match on inventory purchases (audit-critical control gap; 2026 audit confirmed for credit facility) + AR invoicing for misc. wholesale customers',
      signalOrLearning: 'Major development: **APG is new majority shareholder** (mandates NetSuite by early 2027). Three-way match has no demonstrable evidence trail today. AP volume ~400/month. Kara (Controller): "This is definitely something we need that we\'re not doing today." Bill.com NOT being replaced.',
      nextStep: 'Sergio/ops team review of proposal. Draft NDA. Pilot entry: AP three-way match.',
    },

    // ─── Channel partnership ───
    {
      account: 'TrueMind (Jude D\'Cunha)',
      contact: 'Jude D\'Cunha (Founder; ex-Accenture executive, ex-Microsoft NA SI partner business)',
      geography: 'Toronto, Canada',
      industry: 'GTM partner — enterprise channel',
      scale: 'Big 4 partners working with him',
      status: 'Channel partnership',
      tier: 'Channel',
      leadSource: 'Inbound',
      erp: 'N/A',
      wedge: 'Two-channel GTM: enterprise ($1B+) one-to-one via Jude\'s C-suite network + mid-market ($20M-$200M) white-labelled via MS Dynamics + Acumatica partner networks',
      signalOrLearning: '**Critical pitch reframe.** Quote: "If you go to the customer today and start to talk about cost reduction, you lost the customer in the first minute. That game is over." Reframe from cost-savings to working capital / DSO / cash predictability / outcome-based milestone pricing. Claims 80% response rate, 30 closures from 100 outreach.',
      nextStep: 'Lever document → call 3 → NDA + commercials.',
    },
    {
      account: 'GoGlobal',
      contact: 'Yong Long Kee (Continuous Improvement / Process — likely under Leh Choon Wong, his old Brenntag SSC boss now Associate Director GBS at GoGlobal)',
      geography: 'Singapore HQ; remote in 40+ countries',
      industry: 'Employer of Record + global business services',
      scale: '~250 employees; 100+ country coverage; direct entities in 80+',
      status: 'Pre-outreach',
      tier: 'Tier 1',
      leadSource: 'Cold research',
      erp: 'Zoho People + Zoho Expense across 64 countries',
      wedge: 'Internal AP / vendor invoice processing inside GBS, expanding to payroll-adjacent reconciliation and the client-facing accounting & tax service line (launched Jan 2025)',
      signalOrLearning: 'Yong Long built Brenntag\'s APAC Finance SSC from zero — Lean Six Sigma Black Belt, dashboard discipline. GoGlobal\'s Dec 2025 thought leadership: **"AI has moved from experimental to essential."** Thesis sale already won internally. SSC builder to SSC builder is the right opener.',
      nextStep: 'Cold outreach: SSC-builder opener. Reference Brenntag work + GoGlobal Jan 2025 service expansion.',
    },
  ],

  crossCuttingSignals: [
    {
      signal: 'Pricing pushback comes in two forms — cost-savings is dead, calculator is missing',
      evidence: [
        'Jude D\'Cunha (TrueMind): "If you go to the customer today and start to talk about cost reduction, you lost the customer in the first minute. That game is over."',
        'Anahita Arora (CFO advisor): "I don\'t fully understand it" — reverse-engineered FTE × time ÷ Neoflo cost herself',
        'Welspun Sudeep wanted explicit PaaS + use-case-as-a-service tiers',
        'Inspire Scott asked about pricing at 33K-location scale',
        '7 of 8 documented client conversations asked some form of "How is this priced?"',
      ],
      implication: '**Two P0 fixes:** (1) Build a working-capital / DSO / cash-predictability narrative that replaces cost-savings as the headline (Jude\'s mandate). (2) Build a pricing calculator with 2-3 complexity tiers (Anahita\'s mandate). Both are P0 unblockers for further enterprise traction.',
    },
    {
      signal: 'Every documented pipeline deal is warm-channel sourced — none from cold outbound',
      evidence: [
        'Zalora — personal connection (Shivam)',
        'Spectrum Brands — KPMG overlap (Utpala)',
        'HCCB — Ashley D\'Souza (CDO friend)',
        'Apparel Group — Evolv.ai referral',
        'Dafiti — Shivam (Zalora CFO, sister company GFG)',
        'Changi — Wharton classmate (Jacqueline Lee)',
        'Select Equity — Wharton (Bill O\'Boyle)',
        'Rimkus — Wharton (Vitali Edrenkine)',
        'iCar Asia + Zurich — Digbijoy (Nipun network)',
        'Lula — Ganesh',
        'JLand, Welspun, Hitachi — SSON Singapore',
        'Flipkart — Shreya warm intro',
        'Boomerang — Warner personal network',
      ],
      implication: '**Pattern 1 quantified.** 25/25 documented prospects came through warm channels. The ICP\'s SDR strategy (Tier 2 cold outreach) has no documented win in this corpus. Either the warm thesis is structural and cold should be deprioritized, or the cold motion needs more time to mature.',
    },
    {
      signal: 'SAP-shop deals are won or lost on VIM displacement, not Stampli/Tipalti comparison',
      evidence: [
        'Coca-Cola — explicit 11-dimension VIM head-to-head',
        'Spectrum — year 5 of S/4HANA migration, IT fully constrained',
        'Welspun — multiple ERP environment, on-prem hard requirement',
        'Hitachi Vantara — SAP shop',
        'HCCB — Coca-Cola system runs on SAP globally',
        'Mitsubishi RtM — Mitsubishi parent SAP standard',
      ],
      implication: 'Build the 11-dimension VIM-displacement battlecard (Coca-Cola structure) within 30 days. Use it on every SAP-shop deal. The IT-veto risk is real — pre-build SAP S/4 + Oracle Fusion integration reference architecture.',
    },
    {
      signal: 'PE-owned and IPO-prep accounts are the highest-urgency segment',
      evidence: [
        'Spectrum Brands — exploring IPO (Roark-owned)',
        'HCCB — ~$1B IPO summer 2026, 73% profit decline FY25',
        'Quince — $10.1B valuation post-Series E, IPO trajectory',
        'Inspire Brands — $2B IPO planned 2026',
        'Oncourse — Apax-backed, $1.66B WBS',
        'Rimkus — HGGC-backed, new CEO Feb 2026',
        'Dossier — APG new majority shareholder, mandating NetSuite by 2027',
      ],
      implication: 'IPO/PE = audit-grade controls + margin pressure + new CFO/CEO regime = vendor-evaluation window. **Build "IPO readiness" pitch variant** — emphasizes audit trail, SOC 2 Type II, multi-entity consolidation, close compression.',
    },
    {
      signal: 'Controllers are the buyer; CFOs are the economic approver',
      evidence: [
        'Anahita Arora (CFO) explicitly: "Strategic CFOs are too removed from invoice operations. The right first contact is controllers and FinOps heads."',
        'Spectrum — VP Controller (Utpala) is the buyer; introducing AP/AR Sr Directors',
        'Dafiti — Fernando is CFO but the actual controllership work sits one level down',
        'Quince — KP is Financial Controller (the buyer); CEO Sid Gupta is economic approver',
        'Inspire — Scott Cane (Sr Director Shared Services) is the buyer; CFO Kate Jaspon is approver',
        'Welspun — Sudeep is the operational buyer; Akhilesh is technical gatekeeper',
        'Dossier — Jodi (CFO) is the buyer at this scale; Sergio (CEO) signs',
      ],
      implication: 'Update ICP primary persona from CFO to Controller / VP Finance. CFO frame becomes "two things: resource unlock + capital unlock, in a compliant privacy-led way." First touch should target Controller, not CFO. **Two grounded sub-patterns:** (1) at multi-entity orgs (Inspire / Apparel-Group / Welspun pattern), the **Shared Services / GBS Director** replaces the entity Controller as primary buyer — Scott Cane (Sr Director Shared Services at Inspire) is the canonical evidence, and the entry conversation should open at that role, not the entity finance leader; (2) at $1B+ public or pre-IPO US enterprises (Spectrum / HCCB / Quince segment), the **Chief Accounting Officer** is the controls-and-audit gate above the Controller — the SOX-evidence pack and auditor relationship must clear before contract. Build the segment-aware first-touch playbook: SEA mid-market = Controller; SEA / Indian conglomerate multi-entity = GBS Director; US upper-mid SAP-shop = Controller with mandatory CAO loop-in by Stage 2; e-invoicing-mandate-driven = Tax Director.',
    },
    {
      signal: 'Multi-product platform thesis validated by ALL "did not buy" conversations',
      evidence: [
        'Hitachi: walked because we were AP-only when they wanted cash app',
        'Spectrum: rejected HighRadius $1.2-1.5M because they wanted AP + AR + deductions + cash app bundle',
        'Anahita: framed multi-process need explicitly',
        'Dafiti: Shivam framed "AI-led solutions to automate Finance" — broad scope ask',
        'Boomerang/Warner: CPA channel needs full multi-process for mid-market',
      ],
      implication: 'Every documented multi-product ask validates the platform bet. Single-product positioning is the structural reason we lose deals.',
    },
    {
      signal: 'Demo-aha moment is consistent: live extraction with confidence scoring on customer\'s own data',
      evidence: [
        'Irvins: leaned in during live handwritten extraction demo',
        'Anahita: "Very clean UX, very easy to use, technically very cool"',
        'Inspire Scott: matching logic walkthrough landed',
        'Dossier: AP demo on three-way match resonated, Kara: "This is definitely something we need"',
        'Flipkart: 50-60 RO templates extracted in demo',
      ],
      implication: 'Restructure every demo: live confidence-scored extraction on customer data within first 10 minutes. Save architecture monologue for technical deep-dive.',
    },
    {
      signal: 'Tier 2 / cold prospects with strong fit but no warm path',
      evidence: [
        'Yoco — Cape Town, $2B+ TPV, 200K+ merchants on 330 employees',
        'Verto — UK/UAE, $25B volume, 47 employees, 6+ entities',
        'Sunday Insurance — Thailand/Indonesia, 1.6M customers',
        'GoGlobal — Singapore EOR, 100+ countries, AI thesis published',
        'Mitsubishi RtM — Singapore, 90+ countries, commodity trading',
      ],
      implication: 'These are excellent fits where we have no warm intro. Warm-network mapping (Wharton, Lightspeed/Peak XV portfolio, Big 4 alumni, IITK) for each is a high-leverage pre-outreach action.',
    },
  ],

  channelPartnerships: [
    {
      partner: 'TrueMind / Jude D\'Cunha',
      nature: 'Embedded Chief Growth Officer + dual-channel GTM (enterprise direct + mid-market white-label via MS Dynamics + Acumatica partner networks)',
      keyTerms: 'Fixed monthly stipend (paid 1st, scales with sales cycle complexity) + revenue share linked to lever/milestone delivery. Baselining is charged. Exclusivity: Neoflo exclusive in financial operations across his ecosystem. White-label means Neoflo invisible to mid-market end customer.',
      fitNote: 'Strong strategic fit. **Critical condition: pitch must reframe from cost-savings to working-capital/outcome-based.** White-label dynamic in mid-market needs internal alignment (no brand equity accrual). Model is new — claimed metrics (80% response, 30 closures from 100 outreach) are projections, not historical.',
    },
    {
      partner: 'EY India (Tax Technology)',
      nature: 'Operational execution layer underneath their India Tax Platform + TFO managed services',
      keyTerms: 'Not yet structured. Partnership conversation, not vendor sale.',
      fitNote: 'Position as augmenting their AI capabilities, not competing. Risk: strong internal tech team building proprietary AI agents. Their AI is platform layer; Neoflo is execution layer. Approach via Nitish Jain (8 mutual LinkedIn connections).',
    },
    {
      partner: 'Boomerang Catapult / Rehmann CPA',
      nature: 'US warm-channel CPA partnership',
      keyTerms: '80/20 revenue share model with mid-market CPAs (per Warner)',
      fitNote: '6-month learning agenda. Validation of US warm-channel motion. Track customers sourced, deal velocity, ACV, margin after rev share.',
    },
  ],

  investorIntel: [],

  pipelineDistribution: {
    byStatus: [
      { status: 'Live', count: 1 },
      { status: 'Active (in motion)', count: 8 },
      { status: 'Pilot scoping', count: 1 },
      { status: 'Pre-outreach (warm)', count: 4 },
      { status: 'Pre-outreach (cold)', count: 5 },
      { status: 'Exploratory', count: 2 },
      { status: 'Stalled', count: 2 },
      { status: 'Lost', count: 1 },
      { status: 'Channel partnership', count: 2 },
      { status: 'Investor', count: 2 },
    ],
    byTier: [
      { tier: 'Tier 1', count: 21 },
      { tier: 'Tier 2', count: 4 },
      { tier: 'Channel', count: 2 },
      { tier: 'Investor', count: 2 },
    ],
    byGeography: [
      { geo: 'SEA (SG/MY/ID/TH/PH/VN)', count: 8 },
      { geo: 'India', count: 5 },
      { geo: 'US', count: 7 },
      { geo: 'UK / EU', count: 2 },
      { geo: 'Africa (SA + Nigeria-network)', count: 2 },
      { geo: 'GCC / Middle East', count: 1 },
      { geo: 'Latin America', count: 1 },
      { geo: 'Global (90+ country)', count: 2 },
    ],
    byIndustry: [
      { industry: 'Fintech / payments / lending', count: 6 },
      { industry: 'E-commerce / D2C / marketplace', count: 5 },
      { industry: 'Insurance', count: 2 },
      { industry: 'CPG / FMCG', count: 3 },
      { industry: 'Conglomerate / industrial', count: 4 },
      { industry: 'Professional services / consulting', count: 4 },
      { industry: 'QSR / restaurants', count: 1 },
      { industry: 'Government / infrastructure', count: 1 },
      { industry: 'Asset management / wealth', count: 2 },
    ],
    bySource: [
      { source: 'Founder personal network', count: 6 },
      { source: 'Wharton MBA network', count: 3 },
      { source: 'Investor portfolio overlap (KPMG, Big 4, Lightspeed/Peak XV)', count: 3 },
      { source: 'SSON / industry events', count: 3 },
      { source: 'Cold research (no warm path yet)', count: 7 },
      { source: 'Inbound (warm)', count: 3 },
      { source: 'Channel partner (CPA / EY / TrueMind)', count: 2 },
    ],
  },
};
