// Drop into: content/workflow-deep.ts
// Deep, drop-down explanations for each of the 28 P2P/O2C/R2R sub-workflows.
// Keyed by `${process}_${number}` to merge with the workflow map at render time.

export type WorkflowDeepExplanation = {
  whatItIs: string;
  detailedSteps: string[];
  dataInputs: string[];
  dataOutputs: string[];
  systemsTouched: string[];
  commonPainPoints: string[];
  whatGoodLooksLike: string;
  industryBenchmarks: string[];
  whyItMatters: string;
};

export const workflowExplanations: Record<string, WorkflowDeepExplanation> = {
  // ─── P2P ───
  P2P_1: {
    whatItIs: `The control point that establishes a supplier's identity, financial details, tax/regulatory status, and compliance standing before any payment can flow. Once active, the vendor record is the spine that every downstream P2P transaction hangs from — invoices match against it, payments execute from it, audits trace to it.`,
    detailedSteps: [
      'Vendor submits onboarding form via supplier portal or email with KYC info (PAN/GST/registration cert), bank details, primary contact, MSME status, beneficial-ownership disclosure',
      'System validates documents in real time — GST API check (LHDN / IRAS / GSTN), PAN verification, MSME registry lookup, registration cert authenticity',
      'Bank account verified via penny-drop (₹1 deposit + name match) or banking API confirmation',
      'Duplicate detection runs fuzzy match against existing vendor master (name + address + tax-ID + bank account)',
      'Compliance screening against sanctions (OFAC, UN, EU), vendor blacklist, internal restricted-vendor list',
      'Approval routing — procurement reviews, AP validates, finance signs off; risk-scored above threshold escalates',
      'Vendor record created in ERP with payment terms, default GL coding, tax registration, withholding rules, currency',
      'Periodic re-validation — annual KYC refresh, document expiry alerts, sanctions list re-screen quarterly',
    ],
    dataInputs: [
      'KYC documents (PAN / Aadhaar / passport for sole props)',
      'GST / VAT / Sales Tax registration',
      'Bank account details (account number, IFSC/SWIFT, beneficiary name)',
      'Company registration certificate (Companies Act / SSM / SECP / ACRA)',
      'Beneficial ownership disclosure',
      'MSME / SME certifications, contracts',
    ],
    dataOutputs: [
      'Active vendor master record',
      'Approval workflow audit trail',
      'Vendor classification (preferred / standard / restricted)',
      'Payment terms + default GL + tax/withholding config',
      'Onboarding compliance certificate',
    ],
    systemsTouched: [
      'ERP vendor master (SAP MD-BP, Oracle TCA, NetSuite Vendors, Dynamics)',
      'Banking verification API (Razorpay, Plaid, Currencycloud)',
      'KYC services (Karza, Refinitiv, Persona)',
      'Sanctions screening (World-Check, Dow Jones)',
      'Contract repo / DocuSign',
    ],
    commonPainPoints: [
      'Manual onboarding takes 2–4 weeks with 80+ emails per vendor',
      'Duplicate vendors created under variant names ("Acme Inc." vs "Acme, Incorporated" vs "Acme India Pvt Ltd")',
      'Bank-detail typos cause first-payment NEFT/ACH failure',
      'GST / MSME certificates expire silently — payments blocked unexpectedly',
      'No periodic re-screening — vendor lands on sanctions list 6 months in, undetected',
      'Same vendor has different payment terms / GL coding across regions',
    ],
    whatGoodLooksLike: `Self-serve vendor portal where suppliers complete onboarding in under 30 minutes. Automated KYC + duplicate detection + bank verification. Time-to-active under 72 hours. Continuous compliance monitoring with proactive expiry / sanctions alerts.`,
    industryBenchmarks: [
      'Manual cycle 2–4 weeks; best-in-class under 3 days (Tipalti claims 24h)',
      '5–8% of unmanaged vendor masters are duplicates',
      '~15% of new-vendor first payments fail without bank pre-validation',
      'SAP S/4 deployments report 30% master data quality issues at go-live',
    ],
    whyItMatters: `Vendor master is the foundation. A bad vendor record breaks payments, distorts spend analytics, creates audit findings, and exposes the company to fraud (vendor impersonation, ghost vendors). Most P2P automation projects fail because the underlying vendor master was never cleaned.`,
  },

  P2P_2: {
    whatItIs: `An internal request-to-buy ("PR") raised, budget-checked, and routed for approval before money is committed; once approved, it converts to a binding PO sent to the vendor. The PO locks price, quantity, terms — and posts as an open commitment against the budget.`,
    detailedSteps: [
      'Requestor (warehouse manager / ops lead / department head) raises PR specifying item, quantity, GL code, cost center, suggested vendor, expected unit price',
      'System runs real-time budget availability check against the cost center; over-budget PRs flagged for finance review',
      'Approval routing through matrix — department head, finance, CFO if above threshold; out-of-office handling auto-delegates',
      'PR approved → PO generated with unique number, locked price/qty/terms, payment terms inherited from vendor master',
      'PO transmitted to vendor (email PDF, EDI, supplier portal) with acknowledgment requested',
      'PO posted to ERP as open commitment — reserves budget; remaining budget visible to other requestors',
      'Vendor acknowledges; if pricing discrepancy, change order (CO) raised and re-approved',
      'Multi-line POs handle partial deliveries — system tracks open quantity per line',
    ],
    dataInputs: [
      'Item / service catalog with contract pricing',
      'Vendor master with payment terms',
      'Budget ledger by cost center',
      'Approval matrix (delegation of authority)',
      'Existing contract terms',
    ],
    dataOutputs: [
      'Numbered PR + approved PR audit trail',
      'Numbered PO (legally binding commitment)',
      'ERP open-commitment posting',
      'Vendor-facing PDF / EDI 850 / supplier-portal record',
      'Budget reservation entry',
    ],
    systemsTouched: [
      'ERP procurement (SAP MM, Oracle Procurement, NetSuite Purchase)',
      'Supplier portal / EDI gateway',
      'Contract repository (Ironclad, Coupa Contracts, ContractWorks)',
      'Budget control module / FP&A tool',
      'Approval workflow engine',
    ],
    commonPainPoints: [
      'Approvals happen in email or Slack outside the system, breaking the audit trail',
      '"PO-flipping" — POs raised after the invoice arrives, defeating the control',
      'Budget checks manual or skipped; finance discovers over-spend at month-end',
      'Single approver becomes the bottleneck and slows everything',
      'Multi-line POs with partial deliveries tracked in side spreadsheets',
      'Maverick spend (15–25% of mid-market spend) bypasses PRs entirely',
    ],
    whatGoodLooksLike: `Mobile-first PR creation in under 2 minutes. Automated approval routing with SLA enforcement and parallel approvals. Real-time budget checks. Contract-aware pricing autofill. PO acknowledgment and change-order workflow built in.`,
    industryBenchmarks: [
      'Manual PR-to-PO cycle 5–10 days; best-in-class under 24 hours',
      '15–25% of mid-market spend is "maverick" (off-PO)',
      '60–70% of POs need at least one change order in unmanaged systems',
    ],
    whyItMatters: `PO discipline is what prevents maverick spend, fraud, and budget overruns. Without it, every downstream P2P workflow inherits the chaos — invoices arrive without matching POs, approvals happen retroactively, and finance has no commitment visibility.`,
  },

  P2P_3: {
    whatItIs: `Confirming that goods or services actually arrived against an open PO. The Goods Receipt Note ("GRN") is the trigger that opens up a PO line for invoice matching — without it, the invoice cannot 3-way match.`,
    detailedSteps: [
      'Delivery arrives at receiving dock or service-completion confirmed by requestor',
      'Receiving team checks against PO — right item, right quantity, condition acceptable',
      'Quantity received posted (full or partial) against PO line; quality issues raised as rejections',
      'For services: Service Entry Sheet (SES) confirmed by requestor as work-completion proxy',
      'GRN posted to ERP — updates PO open quantity, accrues GR/IR (Goods Receipt / Invoice Receipt) provision',
      'Quality rejections trigger debit-memo or vendor-return workflow',
      'Partial-delivery tracking — system maintains running open balance per PO line',
    ],
    dataInputs: [
      'Open PO with line-level open quantity',
      'Receiving document (delivery note / packing list)',
      'Quality inspection result',
      'Damaged/short claim documentation',
    ],
    dataOutputs: [
      'GRN posted in ERP',
      'GR/IR accrual entry to GL',
      'Updated open-PO balance',
      'Quality rejection / debit memo if applicable',
    ],
    systemsTouched: [
      'ERP receiving (SAP MM Goods Receipt, Oracle Receiving, NetSuite Item Receipt)',
      'WMS / inventory management',
      'Quality management module',
      'Mobile receiving app for warehouse staff',
    ],
    commonPainPoints: [
      'GRNs posted late or in batches — invoices arrive before GRN exists and get blocked',
      'Partial deliveries tracked in spreadsheets, not the ERP',
      'Quality rejections happen but never get a credit note from vendor',
      'For services, SES sign-off lives in email — no system trail',
      'GR/IR accruals not cleared cleanly — month-end reconciliation pain',
    ],
    whatGoodLooksLike: `Mobile receiving on a barcode scanner; GRN posted within minutes of delivery. Service receipts confirmed via mobile app by the requestor. Real-time GR/IR clearing visible to AP team. Quality rejections auto-trigger vendor debit memo.`,
    industryBenchmarks: [
      'Best-in-class GRN posting time under 2 hours from delivery',
      'Mid-market typically posts within 24–72 hours',
      'GR/IR clearing accounts hold 1–3% of total spend at any time in unmanaged systems',
    ],
    whyItMatters: `Goods receipt is the system's view of "we got what we asked for." Without it, the 3-way match fails, payments stall, and AP spends time chasing the warehouse instead of processing invoices. Services GRN is even messier and is where most enterprise services-spend leakage occurs.`,
  },

  P2P_4: {
    whatItIs: `The single most-automated workflow in P2P: capturing supplier invoices from any channel (email, EDI, portal, paper), extracting structured data via OCR/AI, validating duplicates and tax compliance, and routing for matching. Where most "AP automation" investment lands.`,
    detailedSteps: [
      'Invoice arrives via email-to-AP inbox, supplier portal upload, EDI 810, or paper scan',
      'OCR + AI extracts header data (vendor, invoice number, date, amount, tax) and line items (qty, unit price, GL hint)',
      'AI suggests the matching PO and GL coding based on history + line-item description',
      'Duplicate detection — exact match (same invoice number + vendor) and near-match (same amount/date with different invoice format)',
      'Tax validation — GST/VAT input-credit eligibility, TDS applicability, e-invoicing IRN/QR validation',
      'Confidence scoring — high-confidence invoices auto-post; low-confidence routes to human review',
      'Auto-coding learns from each correction — touch ratio (% of invoices auto-posted with no human touch) improves over time',
      'Output: invoice ready for 3-way match with PO + GRN',
    ],
    dataInputs: [
      'Invoice document (PDF, image, EDI 810, e-invoice IRN)',
      'Vendor master',
      'Open POs and GRNs',
      'Historical GL coding patterns per vendor',
      'Tax / e-invoicing rules per jurisdiction',
    ],
    dataOutputs: [
      'Structured invoice record with header + line items',
      'Suggested PO match and GL coding',
      'Duplicate-detection result',
      'Tax validation result (input-credit eligibility, TDS, e-invoicing compliance)',
      'Confidence score',
    ],
    systemsTouched: [
      'OCR / AI extraction (Stampli Billy, Vic.ai, Staple, Nanonets, Tipalti AI)',
      'ERP AP module (SAP FI, Oracle AP, NetSuite Bills)',
      'E-invoicing rails (MyInvois, InvoiceNow, e-Faktur, GSTN)',
      'Email / supplier portal / EDI gateway',
      'Document storage (S3, SharePoint, GDrive)',
    ],
    commonPainPoints: [
      'Invoices arrive in 12 different formats from one vendor',
      'OCR confidence is uneven on non-standard formats (handwritten, photo of paper, regional scripts)',
      'Duplicate detection misses near-duplicates (resubmitted invoice with one-character change)',
      'GL coding inconsistent because three AP clerks code the same vendor differently',
      'E-invoicing mandate (MyInvois / e-Faktur) means non-compliant invoices block payment automatically',
      'High-volume vendors (utilities, telcos) need bespoke parsing rules',
    ],
    whatGoodLooksLike: `Auto-extraction with >90% accuracy on first-pass for known vendor formats. Touch ratio (autonomous posting %) at 70–90%. Duplicate detection catches both exact and near-matches. E-invoicing compliance validated at capture. Learning loop — every correction trains the model for that vendor.`,
    industryBenchmarks: [
      'Stampli touch-ratio benchmark 65–80% on mid-market AP',
      'Vic.ai claims 80–95% autonomy on customer roster',
      'SAP VIM template-based OCR typically <60% first-pass',
      'OCR-primitive vendors (Nanonets, Cogniquest) at ₹1.6–4 per invoice',
      '30–40% of invoices fail clean first-pass match in unmanaged systems',
    ],
    whyItMatters: `This is where automation ROI is most measurable. Every percentage point of touch ratio = X hours saved per AP FTE per month. It's also the layer most attacked by AI-native challengers (Vic.ai, Stuut). The strategic question is not "do we automate" but "how high does our touch ratio go and how fast."`,
  },

  P2P_5: {
    whatItIs: `The control check that confirms PO + GRN + Invoice all agree before payment is approved. Quantity, price, and tax must line up within tolerance. This is where most P2P pain lives — 30–40% of invoices fail clean match the first time.`,
    detailedSteps: [
      'System loads PO header + lines, GRN header + received quantity, Invoice header + lines',
      'Three-way comparison runs: PO qty vs GRN qty vs Invoice qty; PO price vs Invoice price; tax calculation vs invoice tax',
      'Within tolerance (e.g., qty ±5%, price ±2%) → clean match → routes to payment approval',
      'Out of tolerance → exception queue with reason code (price variance, qty short, tax mismatch, etc.)',
      'Exception assigned to investigator (AP clerk, buyer, requestor) with SLA',
      'Investigator works the exception — checks with vendor, requests credit note, confirms receipt, etc.',
      'Resolution recorded in audit trail; either matched or rejected with vendor communication',
      'Two-way match (PO + Invoice, no GRN) handles services / pre-paid items per configuration',
    ],
    dataInputs: [
      'Open PO with prices and quantities',
      'GRN with received quantities',
      'Captured invoice with line items',
      'Tolerance rules (per vendor / per category / global)',
      'Tax calculation rules per jurisdiction',
    ],
    dataOutputs: [
      'Match status (clean / exception / rejected)',
      'Exception queue items with reason codes',
      'Audit trail of resolution',
      'Approved-for-payment invoices',
    ],
    systemsTouched: [
      'ERP AP / matching engine',
      'Workflow engine for exception routing',
      'Vendor communication channel (portal / email)',
      'Tax engine (Avalara, Sovos, native)',
    ],
    commonPainPoints: [
      '30–40% of invoices fail clean first-pass match',
      'Each exception takes 15–30 minutes of human investigation',
      'Common reasons: missing GRN, price variance, partial delivery, tax mismatch, currency conversion error',
      'Invoices sit in exception queues for days; vendors call asking why they haven\'t been paid',
      'Tolerance rules set globally instead of per-vendor — too tight or too loose',
      'No learning — same exception type recurs every month with no automation',
    ],
    whatGoodLooksLike: `>80% clean first-pass match. Per-vendor tolerance rules learned from history. Exception queue UX shows full context (PO, GRN, invoice, communications) on one screen. AI suggests resolution path. Vendor self-service for resolving variances directly.`,
    industryBenchmarks: [
      'Best-in-class first-pass match >80%',
      'Mid-market typical 50–70%',
      'Each exception = 15–30 minutes manual work',
      'Stampli claims highest exception-resolution speed via in-product chat with vendor',
    ],
    whyItMatters: `This is where AP teams spend 60–70% of their time. The match is technically simple; the exception handling is the hard part. Vendor relationships break here — late payments, calls, disputes. The autonomy story (Vic.ai) is fundamentally about making this layer thinner.`,
  },

  P2P_6: {
    whatItIs: `The structured human approval flow for invoices that pass matching but still require sign-off based on amount, GL code, cost center, or vendor risk. Distinct from PR/PO approval — this is the final hold before payment release.`,
    detailedSteps: [
      'Invoice (3-way matched) enters approval queue',
      'Routing rules evaluate: amount threshold, GL code, cost center, vendor risk score',
      'Approver(s) notified — email, Slack, mobile push',
      'Approver reviews invoice in context (PO, GRN, contract, prior history)',
      'Approves, rejects with reason, or requests more info from AP',
      'Multi-step approval (e.g., dept head → CFO above threshold) with parallel or sequential paths',
      'Out-of-office auto-delegates to backup approver',
      'Approved invoices flow to payment queue; rejections route back to AP for resolution',
    ],
    dataInputs: [
      'Approval matrix (delegation of authority) by amount / GL / cost center',
      'User org chart with delegation rules',
      'Invoice with full context (PO, GRN, history)',
    ],
    dataOutputs: [
      'Approved invoice ready for payment run',
      'Audit trail with approver, timestamp, comments',
      'SLA / aging metrics on approval queues',
    ],
    systemsTouched: [
      'Workflow engine',
      'Email / Slack / mobile notification',
      'ERP AP',
      'Approval-matrix configuration',
    ],
    commonPainPoints: [
      'Approval routing in Slack/email outside the system — no audit trail',
      'One bottleneck approver delays everything — no parallel paths',
      'Approver doesn\'t have context (no PO link, no prior invoice history visible)',
      'Out-of-office breaks routing — manual workaround',
      '"Rubber stamp" approvals where reviewer just clicks approve without checking',
    ],
    whatGoodLooksLike: `Mobile-first approval UI with full invoice + history + PO + contract on one screen. Parallel and sequential routing supported. SLA enforcement with auto-escalation. Anomaly detection flags unusual invoices for closer review (10x normal amount, new vendor, weekend invoice).`,
    industryBenchmarks: [
      'Mid-market median approval time 1–3 days',
      'Best-in-class under 8 hours',
      'Stampli claims average sub-1-day approval cycle through in-context conversation',
    ],
    whyItMatters: `Approval workflow is the visible "control" surface — auditors examine it, executives experience it on their phones. Bad UX here drives shadow approvals (Slack messages, verbal OK). Good UX here is one of the highest-leverage UX investments in AP.`,
  },

  P2P_7: {
    whatItIs: `Actually paying the vendor. Generating bank files (NEFT/RTGS/ACH/SWIFT/FAST), routing through dual approval, releasing funds, capturing UTR/reference, sending remittance advice, and reconciling against the AP ledger.`,
    detailedSteps: [
      'Approved invoices selected for payment run by due date and discount eligibility',
      'Payment proposal generated — list of invoices, amounts, banking details, currency',
      'Treasury reviews; CFO approves for large runs',
      'Bank file generated in correct format per rail (NEFT/RTGS/ACH/SWIFT MT103/FAST/SEPA/PayNow)',
      'File submitted to bank (manual upload, host-to-host, API)',
      'Bank confirms each payment; failures flagged in real-time',
      'UTR / reference captured back into ERP; invoice marked paid',
      'Remittance advice sent to vendor with invoice references for cash application',
      'GL entries posted: AP debit, Bank credit; intercompany payments handled separately',
    ],
    dataInputs: [
      'Approved invoices with payment terms',
      'Bank account configuration per entity per currency',
      'FX rates for cross-currency payments',
      'Early-payment discount terms',
    ],
    dataOutputs: [
      'Bank file in NEFT/RTGS/ACH/SWIFT/FAST format',
      'Payment confirmation + UTR/reference',
      'GL posting (AP cleared, Bank debited)',
      'Remittance advice to vendor',
      'Payment failure exception',
    ],
    systemsTouched: [
      'Banking host-to-host or APIs (Razorpay, Aspire, banks)',
      'FX provider for cross-currency (Currencycloud, Wise, banks)',
      'ERP payment module',
      'Treasury management (Kyriba, GTreasury)',
    ],
    commonPainPoints: [
      'Bank files in wrong format get rejected — re-upload required',
      'Payment failures (closed account, wrong IFSC) not flagged in real-time',
      'Remittance advice doesn\'t go to vendor — they call AP asking "did you pay me?"',
      'Cash application on vendor side fails because no remittance reference',
      'Multi-currency payments add FX complexity — reconciliation breaks',
      'Compliance (cross-border, SWIFT GPI tracking) not built in',
    ],
    whatGoodLooksLike: `Same-day NEFT for SG/IN/MY, ACH next-day for US, SWIFT GPI for cross-border with full traceability. Auto-generated remittance with PO + invoice references. Real-time payment-failure alerts with retry workflow. Multi-rail support per jurisdiction (FAST in SG, GIRO in MY, PayNow consumer, NEFT/RTGS in IN).`,
    industryBenchmarks: [
      'Tipalti supports 196 countries + 120 currencies — global benchmark',
      'Bill.com BILL Network handles US ACH at scale',
      'AvidXchange AvidPay Network for vertical-specific',
      'Peakflo native FAST/GIRO/PayNow for SEA',
    ],
    whyItMatters: `Payments is where money moves — the highest-stakes layer. Failure here is felt directly by vendors. Also where most AP automation companies actually monetize — Tipalti, Bill, AvidXchange all earn primary revenue on per-transaction fees. Whether to charge per-transaction is a strategic positioning choice.`,
  },

  P2P_8: {
    whatItIs: `Vendor-facing portal for invoice submission, payment-status tracking, document upload, and dispute raising. Reduces inbound email volume to AP and gives vendors visibility — the single biggest source of AP team firefighting.`,
    detailedSteps: [
      'Vendor logs in via SSO or credentials',
      'Sees list of all open invoices with current status (matching, approval, paid, on-hold)',
      'Submits new invoice with PO reference attached',
      'Receives notification of any matching exception with explanation',
      'Communicates with AP directly via in-portal messaging',
      'Downloads remittance advice and statements',
      'Updates own master data (bank changes, contact info, certifications)',
    ],
    dataInputs: [
      'Vendor login + permissions',
      'Open invoice records',
      'Payment history',
      'PO references + status',
    ],
    dataOutputs: [
      'Vendor-submitted invoices',
      'Vendor-facing payment status',
      'Vendor-side master data updates (with re-approval)',
      'In-portal communication log',
    ],
    systemsTouched: [
      'Identity provider for vendor SSO',
      'ERP for AP / vendor data',
      'Document storage',
      'Notification engine',
    ],
    commonPainPoints: [
      'Vendors don\'t know if/when they were paid — flood of "paid yet?" emails',
      'No self-service for bank-detail change — paper-based, vulnerable to fraud (BEC scams)',
      'Vendor portal exists but is rarely adopted because UX is poor',
      'Different portal per buyer means vendors juggle 10+ logins',
    ],
    whatGoodLooksLike: `Modern UX, mobile-friendly, SSO-enabled. <30 seconds to check status of any invoice. Bank-detail changes routed through MFA + buyer approval workflow. In-portal chat replaces 80% of vendor-AP email volume.`,
    industryBenchmarks: [
      'Coupa Supplier Portal and Ariba Network are network-effect leaders',
      'Tipalti Supplier Hub is best-in-class for the SMB-vendor side',
      'Stampli\'s in-product chat doubles as supplier comms — different paradigm',
      'Without a portal, AP teams spend ~20% of time on "paid yet?" inquiries',
    ],
    whyItMatters: `Vendor self-service is the single highest-ROI AP-team productivity lever after invoice extraction. It also reduces fraud risk (BEC bank-change scams) when bank-detail changes route through proper workflow. Strategic value: turns vendors into network participants instead of email senders.`,
  },

  P2P_9: {
    whatItIs: `Visibility layer on top of P2P data — vendor concentration, maverick spend, savings opportunities, contract compliance, category trends. Where finance and procurement turn transaction data into strategic decisions.`,
    detailedSteps: [
      'Aggregate spend across vendors, categories, cost centers, entities',
      'Classify spend by category using AI / commodity codes (UNSPSC)',
      'Detect maverick spend (off-PO purchases) and quantify size',
      'Vendor concentration analysis — top vendors, single-source risks',
      'Contract compliance — billing matches contract terms? Volume discounts triggered?',
      'Savings opportunity surfacing — duplicate vendors, off-contract pricing, payment-term improvements',
      'Forecasting — next quarter spend by category based on historical and committed',
    ],
    dataInputs: [
      'AP transaction history (paid invoices)',
      'Open POs and PRs (committed spend)',
      'Vendor master with classification',
      'Contract terms',
      'Category taxonomy',
    ],
    dataOutputs: [
      'Spend dashboards by dimension (vendor, category, entity, time)',
      'Maverick spend reports',
      'Savings recommendations',
      'Vendor concentration / risk heatmaps',
      'Forecasted spend',
    ],
    systemsTouched: [
      'Data warehouse (Snowflake, BigQuery)',
      'BI tool (Tableau, Power BI, Looker)',
      'Procurement intelligence (Coupa Spend Analytics, SAP Ariba Spend, Sievo)',
    ],
    commonPainPoints: [
      'Spend data lives in 5 different systems — manual consolidation in Excel',
      'Category classification done by hand — inconsistent and stale',
      'Reports are monthly, not real-time',
      'Maverick spend never quantified — finance suspects it but can\'t prove',
      'Savings recommendations are theoretical, no enforcement loop',
    ],
    whatGoodLooksLike: `Real-time spend dashboards refreshed within minutes of invoice posting. AI-categorized spend with >90% accuracy. Active maverick-spend alerts that loop back into PR/PO controls. Quantified savings opportunities with implementation tracking. Forecast accuracy within 5%.`,
    industryBenchmarks: [
      'Coupa Spend Analytics is the enterprise leader',
      'Maverick spend in unmanaged mid-market: 15–25% of total spend',
      'Best-in-class category coverage: >95% of spend categorized',
    ],
    whyItMatters: `Spend analytics is the natural P1 expansion off invoice processing — same data, new value. For Neoflo, this is also where cross-customer benchmarking eventually becomes defensible (with privacy guards) — comparative spend insights across the SEA mid-market customer base.`,
  },

  P2P_10: {
    whatItIs: `Employee expense claims, receipt OCR, approval, card reconciliation, mileage, per-diem. Adjacent workflow but has a different buyer (HR/Finance shared) and different UX paradigm than core AP.`,
    detailedSteps: [
      'Employee incurs expense (card swipe, cash, mileage)',
      'Submits expense report with receipts (mobile photo, email forward)',
      'OCR extracts merchant, amount, date, category from receipt',
      'Per-diem and policy rules auto-applied (max meal $X, mileage $0.65/mile)',
      'Manager approves; finance reviews policy compliance',
      'Reimbursement to employee or card-reconciliation against corporate-card statement',
      'GL posting to expense GLs',
    ],
    dataInputs: [
      'Receipts',
      'Card transactions (corp card feed)',
      'Mileage records',
      'Travel itinerary',
      'Expense policy',
    ],
    dataOutputs: [
      'Approved expense report',
      'Reimbursement payment',
      'GL posting',
      'Policy violation alerts',
    ],
    systemsTouched: [
      'Mobile expense app',
      'Corporate card provider',
      'OCR service',
      'ERP / payroll for reimbursement',
    ],
    commonPainPoints: [
      'Employees forget to submit; finance chases at month-end',
      'Receipt-image quality issues',
      'Policy violations only caught after expense incurred',
      'Manager approval is rubber-stamp',
      'Card-recon between corp card and expense reports is manual',
    ],
    whatGoodLooksLike: `Submit-on-the-go via mobile. AI auto-categorizes and applies policy. Pre-approval for trips above threshold. Real-time card-feed reconciliation. Sub-1-day reimbursement.`,
    industryBenchmarks: [
      'SAP Concur is the global leader',
      'Ramp/Brex bundle T&E with cards (different distribution model)',
      'Spenmo, Volopay are the SEA SMB players',
    ],
    whyItMatters: `Different buyer (HR/Finance shared), different UX, different distribution model (often bundled with corporate cards). Out of scope for our platform thesis but worth tracking — Ramp/Brex use T&E as the wedge into broader spend management.`,
  },

  // ─── O2C ───
  O2C_1: {
    whatItIs: `Setting up customers in your system and deciding how much credit to extend them. KYC, credit-bureau checks, credit-limit assignment, payment-terms decision, ongoing credit monitoring as their payment behavior evolves.`,
    detailedSteps: [
      'Customer submits onboarding info (registration cert, GST/VAT, bank, contact)',
      'Credit-bureau check (Experian, D&B, CIBIL, internal scoring)',
      'Risk scoring — industry, geography, payment history (if any), credit utilization',
      'Credit limit assigned based on risk + expected order volume',
      'Payment terms decided (Net 15 / Net 30 / Net 60 / Letter of Credit)',
      'Active customer record created in ERP',
      'Periodic re-scoring — credit utilization, payment behavior, market events',
      'Limit adjustments — increased for good payers, reduced for late ones',
    ],
    dataInputs: [
      'Customer KYC docs',
      'Credit bureau data',
      'Bank reference',
      'Internal credit-policy rules',
      'Historical payment behavior (if existing)',
    ],
    dataOutputs: [
      'Active customer record',
      'Assigned credit limit + payment terms',
      'Risk-tier classification',
      'Periodic credit-monitoring reports',
    ],
    systemsTouched: [
      'Credit bureau APIs',
      'ERP customer master (SAP CRM, Oracle TCA, NetSuite Customers)',
      'Internal credit-scoring model',
      'KYC service',
    ],
    commonPainPoints: [
      'Onboarding takes 2–4 weeks — slows time-to-revenue',
      'Credit data stale by the time it\'s used',
      'Risk profiles never updated as customer payment behavior changes',
      'Limit decisions arbitrary, not policy-driven',
      'Single-system credit checks miss subsidiary / parent relationships',
    ],
    whatGoodLooksLike: `Self-serve customer onboarding portal with API-based credit checks; time-to-active under 24 hours for low-risk segments. Real-time credit-utilization dashboards. Auto re-scoring quarterly. Policy-driven limit decisions with override workflow.`,
    industryBenchmarks: [
      'HighRadius Credit Cloud sets the enterprise bar',
      'Best-in-class onboarding under 24 hours',
      'Mid-market typical 1–2 weeks',
    ],
    whyItMatters: `Bad customer onboarding = bad debt. Credit decisions made at onboarding compound through every order, invoice, and collection later. Most DSO problems trace back to lax credit at onboarding.`,
  },

  O2C_2: {
    whatItIs: `Taking in a customer order, validating it, and booking it. Inventory check, pricing application, credit-limit check, fulfillment trigger. Order management is ERP territory — we integrate, we don't replace.`,
    detailedSteps: [
      'Order arrives (email, EDI 850, portal, sales rep)',
      'Inventory availability check',
      'Pricing applied — contract, list price, customer-specific discount',
      'Credit-limit check — does this order fit within approved limit?',
      'Order accepted and pushed to fulfillment',
      'Order acknowledgment sent to customer',
      'Backorder handling for partial availability',
    ],
    dataInputs: [
      'Customer master with credit limit',
      'Inventory levels',
      'Pricing rules',
      'Contract terms',
    ],
    dataOutputs: [
      'Booked sales order',
      'Acknowledgment to customer',
      'Fulfillment trigger to warehouse',
      'Reserved inventory',
    ],
    systemsTouched: [
      'ERP sales (SAP SD, Oracle OM, NetSuite)',
      'WMS for inventory',
      'CPQ for complex pricing',
    ],
    commonPainPoints: [
      'Orders come via too many channels (email, fax, EDI, portal)',
      'Credit checks manual or skipped',
      'Pricing errors common (wrong contract version)',
      'Backorder visibility poor',
    ],
    whatGoodLooksLike: `Single order capture across channels. Real-time inventory and credit check. Automated acknowledgment within minutes. Backorder management with customer choice (wait vs cancel).`,
    industryBenchmarks: [
      'Esker Order-to-Cash leads on order entry automation',
      'SAP SD / Oracle OM / NetSuite are the ERP defaults',
    ],
    whyItMatters: `Order errors compound downstream — wrong order = wrong invoice = wrong cash collected. Out of our scope; we integrate with whatever order system the customer runs.`,
  },

  O2C_3: {
    whatItIs: `Generating the invoice from delivered orders, applying contract pricing, taxes, discounts, and any customer-specific terms. Critically — for SEA — submitting the invoice to the tax authority via e-invoicing rails (MyInvois, InvoiceNow, e-Faktur).`,
    detailedSteps: [
      'Delivery confirmation triggers billing eligibility',
      'Invoice generated with contract pricing, tax (GST/VAT), discounts, freight',
      'E-invoicing submission to tax authority for jurisdictions with mandates (MY MyInvois, SG InvoiceNow, ID e-Faktur, PH BIR)',
      'Tax-authority validation returns IRN/QR code; invoice attaches it',
      'Invoice transmitted to customer via email PDF, EDI 810, customer portal, or PEPPOL',
      'AR posting — Receivable debit, Revenue credit, Tax credit',
      'Recurring billing (subscriptions, retainers) auto-generated on schedule',
    ],
    dataInputs: [
      'Delivered orders / service-completion confirmation',
      'Contract pricing',
      'Tax rules per jurisdiction',
      'Customer billing preferences',
      'E-invoicing certification per jurisdiction',
    ],
    dataOutputs: [
      'Issued invoice (PDF + structured data)',
      'IRN / QR code (e-invoicing jurisdictions)',
      'AR posting in GL',
      'Invoice transmitted to customer',
    ],
    systemsTouched: [
      'ERP AR / billing module',
      'E-invoicing rails (LHDN MyInvois, IMDA InvoiceNow PEPPOL, DGT e-Faktur, BIR EIS)',
      'Tax engine (Avalara, Sovos, ClearTax, native)',
      'Customer delivery channels (email, portal, EDI, PEPPOL access point)',
    ],
    commonPainPoints: [
      'Invoice errors (wrong pricing, wrong tax) cause downstream disputes',
      'E-invoicing compliance varies by country and changes frequently',
      'Manual invoice generation slow and error-prone',
      'Recurring billing logic complex (proration, mid-cycle changes, tier upgrades)',
      'Multi-jurisdiction tax (GST/VAT/SST/withholding) is jurisdiction-by-jurisdiction work',
    ],
    whatGoodLooksLike: `Auto-billing on delivery confirmation. Native e-invoicing in every required jurisdiction. <1% billing error rate. Recurring billing with mid-cycle proration. Real-time tax validation.`,
    industryBenchmarks: [
      'Sovos and Avalara lead global e-invoicing compliance',
      'ClearTax leads India + expanding SEA',
      'HighRadius eInvoicing Cloud bundled with their AR suite',
    ],
    whyItMatters: `**This is the highest-leverage GTM trigger in SEA right now.** MyInvois mandatory rollout through 2026 means every Malaysian mid-market business must comply. Native e-invoicing turns compliance into the wedge — buyers don't shop, they're forced to choose.`,
  },

  O2C_4: {
    whatItIs: `The receivables ledger. Tracking what customers owe through aging buckets (0–30, 31–60, 61–90, 90+), monitoring DSO (Days Sales Outstanding), measuring exposure. The CFO-visible layer of cash visibility.`,
    detailedSteps: [
      'Issued invoices land as open receivables',
      'Aged buckets calculated daily',
      'DSO calculated as (AR ÷ Revenue) × Days, by entity, region, customer',
      'Cash exposure dashboards refreshed real-time',
      'Customer-level history — payment behavior, average days to pay',
      'Promise-to-pay tracking integrated with collections',
      'Bad debt provision calculated based on aging × risk',
    ],
    dataInputs: [
      'Open invoices',
      'Cash applied to invoices',
      'Customer master',
      'Aging rules',
      'Bad-debt provision policy',
    ],
    dataOutputs: [
      'Aged AR report',
      'DSO metrics',
      'Customer-level exposure dashboards',
      'Bad-debt provisions',
    ],
    systemsTouched: [
      'ERP AR sub-ledger',
      'BI dashboards',
      'Treasury cash flow systems',
    ],
    commonPainPoints: [
      'AR data lives in ERP exports; dashboards in monthly Excel',
      'CFOs have no real-time view of cash exposure',
      'Aging buckets calculated inconsistently across entities',
      'No customer-level early warning (rising days-to-pay) until crisis',
    ],
    whatGoodLooksLike: `Real-time AR with multi-entity rollup. Customer-level early-warning indicators. Drill-down from DSO to invoice-level. Forecasted collections for next 30/60/90 days.`,
    industryBenchmarks: [
      'Mid-market median DSO 60–90 days',
      'Best-in-class under 45 days',
      'HighRadius / Sidetrade target 5–15 day DSO compression',
    ],
    whyItMatters: `Real-time AR is what makes cash visible to the CFO. Most mid-market CFOs see AR as a monthly Excel report, not a real-time number. Closing this gap is the visible value of any O2C platform sale.`,
  },

  O2C_5: {
    whatItIs: `Chasing customers who haven't paid. Sequence of reminders — polite, firm, escalating — sent via email/SMS/phone. Promise-to-pay tracked. Collectors prioritize by value × overdue × risk. Voice AI is a category-defining feature for SEA.`,
    detailedSteps: [
      'Aging report identifies overdue invoices',
      'Auto-dunning sequence triggered: Day 31 polite reminder, Day 45 firmer, Day 60 escalation, Day 90 collections-grade',
      'Channel mix — email, SMS, voice (AI or human)',
      'Promise-to-pay logged when customer commits to date',
      'Collector queue prioritized by score (amount × overdue × risk × likelihood-to-pay)',
      'Disputed invoices excluded from dunning (don\'t harass legitimate disputes)',
      'Escalation to legal / collections agency for >90-day high-value',
      'Outcome tracked — paid, promise-to-pay, dispute, written off',
    ],
    dataInputs: [
      'Aging buckets',
      'Customer payment history',
      'Customer relationship signals (sales-flagged accounts to handle gently)',
      'Dunning sequence templates per segment',
    ],
    dataOutputs: [
      'Sent reminders + delivery status',
      'Promise-to-pay records',
      'Collector activity log',
      'Days saved on DSO',
    ],
    systemsTouched: [
      'Email / SMS / voice channels',
      'CRM for relationship signals',
      'Collections case-management system',
    ],
    commonPainPoints: [
      'Reminders ad-hoc, not sequenced',
      'Collectors work from spreadsheets',
      'Promise-to-pay not tracked — same conversation repeated',
      'Customers in dispute still get dunned, damaging relationships',
      'No prioritization — small / large invoices treated identically',
    ],
    whatGoodLooksLike: `Automated dunning sequences personalized by customer segment. Voice AI handles first-pass collections in local languages. Promise-to-pay logged automatically from email/voice. Disputes auto-suppress dunning. Collector dashboard prioritizes by ROI.`,
    industryBenchmarks: [
      'HighRadius Collections Cloud benchmark',
      'Sidetrade Aimie autonomous collections',
      'Peakflo voice AI in 12+ languages — SEA category-defining',
      'Stuut documents 6–10 day deploys',
      'PerkinElmer (Stuut customer) reduced overdue 50% → 15% in 1 year',
    ],
    whyItMatters: `Collections is where the cash actually arrives. Every day of DSO compression = X days of working capital saved. Voice AI specifically is reshaping the SEA market — Peakflo's headline feature.`,
  },

  O2C_6: {
    whatItIs: `An autonomous AI voice agent that calls overdue customers, holds natural-language conversations in local languages, handles common objections, and logs promise-to-pay. Category-defining in SEA where phone-based collections are culturally normal.`,
    detailedSteps: [
      'Trigger — overdue invoice past dunning sequence escalation point',
      'Voice AI initiates call to customer accounts contact',
      'AI handles intro, identifies invoice context, asks for payment',
      'Common objections handled (cash flow tight, dispute, paid already with reference)',
      'AI logs outcome — promise-to-pay date, dispute reason, hand-off to human',
      'Recording + transcript stored for compliance',
      'Follow-up actions auto-scheduled per outcome',
    ],
    dataInputs: [
      'Customer phone + language preference',
      'Invoice context + history',
      'Conversation script + objection-handling tree',
      'Compliance constraints (recording disclosure, dialing hours)',
    ],
    dataOutputs: [
      'Promise-to-pay date',
      'Recorded call + transcript',
      'Dispute logged',
      'Hand-off to human collector with context',
    ],
    systemsTouched: [
      'Voice AI infrastructure (Bland.ai, Retell, Vapi, custom)',
      'Telephony (Twilio, Plivo, regional carriers)',
      'CRM for context',
      'Compliance / call-recording storage',
    ],
    commonPainPoints: [
      'Cultural fit — voice AI works in SEA but feels intrusive in US/UK',
      'Multi-language support (Bahasa, Mandarin, Vietnamese) is hard to build well',
      'Compliance — recording disclosure laws, allowed dialing hours per jurisdiction',
      'Voice quality on cellular networks',
      'Hand-off UX when AI escalates to human',
    ],
    whatGoodLooksLike: `Voice AI handles 70%+ of first-call collections. 12+ language support including SEA regional. Natural conversation, not robotic. Hand-off to human collector with full context. Compliance with local recording / DNC laws.`,
    industryBenchmarks: [
      'Peakflo claims 12+ language voice AI — category-defining',
      'Sidetrade Aimie + Stuut for English/EU markets',
    ],
    whyItMatters: `Voice AI is structurally Peakflo-defined for SEA. Our build/partner decision here directly affects O2C win rate against them. Underlying voice infrastructure (Bland.ai, Retell, Vapi) is commoditizing — partner-test in 2026 is the right path.`,
  },

  O2C_7: {
    whatItIs: `Matching incoming bank payments to open invoices. Sounds simple, breaks constantly: lump-sum payments across invoices, short-pays, multi-currency, missing references. Eats 20–30% of AR team time at most companies.`,
    detailedSteps: [
      'Bank feed lands payments in real-time or end-of-day',
      'Payment reference extracted (UTR, invoice number, customer name)',
      'Match attempted — exact (full payment for one invoice) or partial (lump sum across many)',
      'AI suggests matches based on amount + customer + history + remittance',
      'Short-pay handling — partial-payment with deduction reason captured',
      'Unallocated cash queue for payments without clear match',
      'Multi-currency conversion + FX gain/loss posting',
      'AR ledger updated; invoice marked paid; remittance acknowledged to customer',
    ],
    dataInputs: [
      'Bank statement feeds (real-time or daily)',
      'Open AR sub-ledger',
      'Customer master',
      'Historical payment patterns',
      'FX rates',
    ],
    dataOutputs: [
      'Cash applied to invoices',
      'Updated AR sub-ledger',
      'Short-pay deduction records',
      'Unallocated cash queue',
      'FX gain/loss posting',
    ],
    systemsTouched: [
      'Banking feeds (host-to-host, plaid, banking API)',
      'ERP AR sub-ledger',
      'Cash app engine (HighRadius Cash App Cloud, Sidetrade)',
      'Reconciliation tool',
    ],
    commonPainPoints: [
      'Customers pay lump sums across multiple invoices',
      'Short-pay (paying less than invoice) without explanation',
      'Wrong / missing reference numbers on bank statements',
      'Multi-currency payments add FX complexity',
      'Manual matching consumes 20–30% of AR team time',
      'Unallocated cash sits in a clearing account for weeks',
    ],
    whatGoodLooksLike: `>95% straight-through cash application. AI handles lump-sum, short-pay, and missing-reference scenarios. FX handled natively. Unallocated cash queue under 1% of monthly inflow. Same-day cash application.`,
    industryBenchmarks: [
      'HighRadius Cash Application Cloud — flagship, claims 90%+ STP',
      'Sidetrade, BlackLine Cash App, Versapay',
      'Best-in-class STP rate >95%',
      'Mid-market typical 60–75% STP',
    ],
    whyItMatters: `**This is exactly what Hitachi asked for and we didn't have.** Cash app is the gating feature for the Hitachi-pattern enterprise buyer. HighRadius monetizes heavily on this; their reject quote ($1.2M+ to Spectrum) creates our opening.`,
  },

  O2C_8: {
    whatItIs: `Resolving why a customer is refusing to pay. Wrong price, short delivery, bad quality, billing error, deduction. Sales handles pricing, ops handles quality/delivery, finance handles billing. Disputes can sit unresolved for weeks because there's no shared system of record.`,
    detailedSteps: [
      'Dispute raised — by customer (inbound) or detected (short-pay with reason)',
      'Dispute logged with reason code, evidence (PO, POD, invoice, communications)',
      'Routed to owner — sales for price, ops for quality/delivery, AR for billing error',
      'Investigation — gather evidence, internal alignment',
      'Decision — credit note issued (if dispute valid), customer pushed for payment (if invalid)',
      'Credit note generated; AR updated; customer notified',
      'For deductions specifically (CPG/retail) — separate workflow handles trade promotion deductions, returns, allowances',
      'Aging dispute report — pressure on internal owners to resolve',
    ],
    dataInputs: [
      'Customer dispute (email, portal, short-pay reason)',
      'Original invoice + PO + POD',
      'Internal communication',
      'Contract terms',
    ],
    dataOutputs: [
      'Dispute case with status',
      'Credit note (if issued)',
      'Updated AR ledger',
      'Resolution time metric',
    ],
    systemsTouched: [
      'Dispute case-management system',
      'CRM (sales involvement)',
      'Quality/operations system',
      'ERP for credit note',
    ],
    commonPainPoints: [
      'Disputes sit in email threads for weeks',
      'No shared system of record between sales, ops, finance',
      'Credit notes issued slowly or incorrectly',
      'Unresolved disputes = aged receivables = bad DSO',
      'CPG/retail deductions (trade promotions) are particularly complex',
    ],
    whatGoodLooksLike: `Single system of record across sales/ops/finance. Average dispute resolution under 7 days. Auto-classification of dispute reason. Customer portal for self-service dispute raising. Deduction-specific workflow for CPG.`,
    industryBenchmarks: [
      'HighRadius Deductions Cloud — best for CPG/retail',
      'Versapay dispute UX is the differentiator',
      'Best-in-class resolution under 7 days; mid-market typical 14–30 days',
    ],
    whyItMatters: `Spectrum specifically asked for deductions automation. CPG/retail buyers have huge deduction volumes (trade promo, returns, freight) that destroy DSO. This is a P0 for our O2C scope.`,
  },

  O2C_9: {
    whatItIs: `Predicting cash inflows from AR, simulating scenarios, modeling DSO compression impact on cash. The analytics layer that turns AR data into FP&A inputs and treasury decisions.`,
    detailedSteps: [
      'Aggregate open AR + payment history + customer behavior',
      'Predict expected payment date per customer per invoice',
      'Roll up into 30/60/90-day cash forecast',
      'Scenarios — what if DSO improves 5 days? What if top 10 customers slow 7 days?',
      'Treasury / FP&A consumes for cash-position planning',
      'Integration with payables forecast for net-cash view',
    ],
    dataInputs: [
      'Open AR with aging',
      'Customer payment behavior history',
      'Promise-to-pay records',
      'Macroeconomic signals (sector slowdown)',
    ],
    dataOutputs: [
      'Cash forecast 30/60/90 days',
      'DSO scenario models',
      'Customer-level expected pay dates',
    ],
    systemsTouched: [
      'AR sub-ledger',
      'FP&A tool (Anaplan, Datarails, Mosaic)',
      'Treasury system',
    ],
    commonPainPoints: [
      'Cash forecasts done in Excel monthly',
      'Forecast accuracy ±20% — useless for treasury planning',
      'No customer-level forecast — top-down extrapolation',
      'No scenario modeling',
    ],
    whatGoodLooksLike: `Daily-refresh cash forecast with <5% variance to actuals. Customer-level prediction. Scenario modeling on-demand. Direct integration with treasury cash positioning.`,
    industryBenchmarks: [
      'Tesorio is the wedge player here',
      'Centime, HighRadius Cash Flow Cloud',
      'Best-in-class forecast accuracy ±5%',
    ],
    whyItMatters: `Natural P1 expansion once AR + cash app are live. The CFO-visible value of "I know exactly what cash is coming in next 30 days" is high. Tesorio built a company on this single workflow — proof there's standalone willingness-to-pay.`,
  },

  O2C_10: {
    whatItIs: `Customer-facing portal for invoice viewing, payment, dispute raising, statement download. The B2B equivalent of "view your bill online" — reduces inbound calls to AR by ~40%.`,
    detailedSteps: [
      'Customer logs in via SSO',
      'Sees all open invoices, payment history, statements',
      'Pays via card, ACH, bank transfer, or local rails (FAST/PayNow/UPI)',
      'Raises disputes with attached evidence',
      'Downloads statements / W9 / tax docs',
      'Updates own contact / billing address',
    ],
    dataInputs: [
      'Customer login + permissions',
      'Open invoices + payment history',
    ],
    dataOutputs: [
      'Customer-initiated payments',
      'Customer-raised disputes',
      'Self-service master data updates',
    ],
    systemsTouched: [
      'Identity provider',
      'Payment gateway',
      'AR sub-ledger',
    ],
    commonPainPoints: [
      'Portal exists but barely used because UX is poor',
      'Different portal per buyer — fatigue',
      'Payment options limited (no local rails)',
      'No mobile experience',
    ],
    whatGoodLooksLike: `Mobile-first UX. SSO supported. Multiple payment options including local rails. Self-service dispute raising. Reduces AR-team email volume 40%+.`,
    industryBenchmarks: [
      'Versapay leads on collaborative buyer-seller portal',
      'Billtrust on payments portal',
      'Bill.com on AP-AR network',
    ],
    whyItMatters: `Customer self-service is the AR equivalent of vendor self-service in P2P — massive efficiency lift. P1 expansion once AR sub-ledger is live.`,
  },

  // ─── R2R ───
  R2R_1: {
    whatItIs: `Drawing the line on the period — deciding what counts as a March transaction and what counts as April. Sub-ledgers (AP/AR/payroll/inventory/fixed assets) freeze; outstanding accruals for unbilled items get posted.`,
    detailedSteps: [
      'Sub-ledger cutoff communicated to all teams',
      'AP confirms all in-period invoices entered (or accrued for unbilled goods received)',
      'AR confirms all delivered orders billed',
      'Payroll accrues for hours worked in late period but paid next month',
      'Depreciation runs on fixed assets',
      'GR/IR clearing — Goods Received Not Invoiced accruals posted',
      'Intercompany cutoff — both sides reconciled',
      'Sub-ledgers technically locked from further period postings',
    ],
    dataInputs: [
      'AP open invoices + GR/IR clearing',
      'AR open orders + delivery confirmations',
      'Payroll hours-worked',
      'Fixed asset register',
      'Intercompany positions',
    ],
    dataOutputs: [
      'Period-locked sub-ledgers',
      'Posted accruals (rent, utilities, payroll, depreciation, GR/IR)',
      'Cutoff confirmation log',
    ],
    systemsTouched: [
      'ERP sub-ledgers (AP, AR, payroll, FA, inventory)',
      'Close management tool (BlackLine, FloQast, Numeric)',
      'Communication channel for cutoff coordination',
    ],
    commonPainPoints: [
      'Sub-ledgers don\'t all freeze at the same time',
      'AP keeps posting period invoices into early next-month',
      'GRNI accruals based on stale data',
      'Intercompany doesn\'t match (one side sent S$10K, other received S$9,995 due to FX/fees)',
      'Payroll accrual gets re-stated three times',
    ],
    whatGoodLooksLike: `Sub-ledger cutoff happens automatically on Day 0 with no manual gates. GR/IR accruals real-time from receiving. Intercompany matched within 1 day. Payroll accrual auto-calculated from time-tracking data. Audit-ready cutoff log.`,
    industryBenchmarks: [
      'Best-in-class close cycle 3–5 days',
      'Mid-market typical 8–15 days',
      'BlackLine, FloQast, Trintech are the close-mgmt incumbents',
    ],
    whyItMatters: `**Cross-process advantage:** as the system of record for AP and AR, our cutoff data is real-time. Standalone close tools depend on ERP feeds that lag. This is the architectural advantage of running P2P+O2C+R2R on one platform.`,
  },

  R2R_2: {
    whatItIs: `All the manual accounting entries that don't come automatically from sub-ledgers — accruals, prepaid amortization, lease accounting, FX revaluation, provisions, deferred tax, one-off adjustments. Each JE has a preparer, reviewer, approver.`,
    detailedSteps: [
      'Preparer pulls supporting evidence (lease schedule, FX rates, accrual workings)',
      'Calculates the entry; drafts in JE workflow tool with attached support',
      'Submits for review; reviewer checks math, GL coding, reasonableness',
      'Approver signs off; JE posts to GL',
      'Audit trail captures preparer, reviewer, approver, evidence, comments',
      'Recurring JEs (monthly accruals) use templates that refresh from data',
      'Reversing entries auto-generated where applicable (accruals reverse next period)',
      'Last-minute / top-side JEs from controller flagged for higher scrutiny',
    ],
    dataInputs: [
      'Lease schedule, FX rates, accrual workings',
      'Prior-period JE templates',
      'Calculation evidence (Excel workings, supporting docs)',
    ],
    dataOutputs: [
      'Posted JEs in GL',
      'JE workflow audit trail',
      'Recurring JE templates',
    ],
    systemsTouched: [
      'JE workflow tool (BlackLine JE, FloQast JE, Numeric)',
      'ERP GL',
      'Document management for evidence',
    ],
    commonPainPoints: [
      'JEs in Excel templates with no version control',
      'Same JE re-prepared every month from scratch instead of template+refresh',
      'Reviewers don\'t have time to check workings; approve based on trust',
      'Last-minute JEs from controller bypass the workflow',
      'Anomalous entries (10x normal amount) sail through because nobody pattern-matches',
    ],
    whatGoodLooksLike: `Template-driven recurring JEs auto-populated from sub-ledger data. AI flags anomalous JEs for closer review. Mobile approval. Full audit trail with one-click drill-down to evidence. Top-side JEs require additional approval.`,
    industryBenchmarks: [
      'BlackLine Journal Entry, FloQast JE, Numeric — workflow leaders',
      'Best-in-class JE cycle <2 days from prep to post',
    ],
    whyItMatters: `Cross-process audit trail across AP/AR/JE is our differentiation. Standalone JE tools have a thin audit trail. AI-flagging anomalous JEs is a differentiator we can build naturally given our cross-process data view.`,
  },

  R2R_3: {
    whatItIs: `Proving that what's in the GL matches what's in the underlying source — bank statements, sub-ledgers, schedules, third-party confirmations. Every balance sheet account gets reconciled. Single biggest time sink in close.`,
    detailedSteps: [
      'List all balance-sheet accounts requiring reconciliation (typically 25–50 for mid-market)',
      'For each, pull GL balance + source data (bank statement, sub-ledger total, schedule)',
      'Auto-match — AI matches GL line to source line',
      'Reconciling items identified — deposits in transit, outstanding cheques, GR/IR open',
      'Preparer documents reconciliation with explanation per item',
      'Reviewer signs off; supporting evidence attached',
      'Aging reconciling items tracked (long-aged items = problem)',
      'Locked once approved',
    ],
    dataInputs: [
      'GL balances',
      'Bank statements, sub-ledger totals, third-party confirmations',
      'Reconciliation templates',
    ],
    dataOutputs: [
      'Approved reconciliations per account',
      'Reconciling-items log',
      'Audit evidence',
    ],
    systemsTouched: [
      'Reconciliation engine (BlackLine Reconciliations, FloQast, Trintech, Numeric)',
      'ERP GL',
      'Bank feeds',
      'Sub-ledger systems',
    ],
    commonPainPoints: [
      '**Single biggest time sink in close** — recs done in Excel templates emailed around',
      'Discrepancies explained as "timing differences" and ignored, then compound',
      'Fixed asset and lease recs particularly painful',
      '"Reconciled" often means "controller signed off" not "every line checked"',
      'Long-aged reconciling items never investigated',
    ],
    whatGoodLooksLike: `Auto-matching covers >85% of lines. Recs ready Day 1 of close. Aging reconciling items prioritized for resolution. Reviewer sees prior-period diff highlighted. Audit drill-down one click.`,
    industryBenchmarks: [
      'BlackLine Reconciliations is the category-defining product',
      'FloQast Excel-native UX — mid-market leader',
      'Numeric AI-native challenger',
      'Best-in-class auto-match rate >85%',
    ],
    whyItMatters: `Reconciliations are where close time concentrates. P0 in our R2R Phase 3 scope. ML-based auto-matching is the UX bar.`,
  },

  R2R_4: {
    whatItIs: `Comparing every P&L and BS line to prior month, prior year, and budget — explaining any movement above threshold. Each variance gets written commentary. Controller and CFO read this before signing off.`,
    detailedSteps: [
      'Trial balance locked',
      'Variance analysis runs across P&L and BS — vs prior month, prior year, budget',
      'Lines exceeding threshold (e.g., >5% or >$X) flagged for explanation',
      'Controller / accountants write commentary per variance — driver, root cause, expected next period',
      'CFO reviews; asks questions; requests adjustments',
      'Top-side adjustments posted; reconciliation re-run if needed',
      'Final sign-off; books considered "closed"',
    ],
    dataInputs: [
      'Locked trial balance current period',
      'Prior month, prior year TB',
      'Budget',
      'Operational data (sales volume, headcount, etc.)',
    ],
    dataOutputs: [
      'Variance analysis report',
      'Written commentary per flagged variance',
      'CFO-approved sign-off',
      'Top-side adjustments (if any)',
    ],
    systemsTouched: [
      'Close mgmt + flux analysis tools (Numeric, FloQast AI, BlackLine)',
      'BI / reporting',
      'Communication channel',
    ],
    commonPainPoints: [
      'Flux analysis done by hand pulling data into Excel',
      '60+ commentary lines written by hand each month',
      'CFO questions trigger another round of rec work',
      'Top-side adjustments at eleventh hour bypass controls',
    ],
    whatGoodLooksLike: `AI generates initial flux commentary; controller refines. CFO sees prior-period commentary side-by-side. Top-side adjustments require additional approval. Variance threshold per account learned over time.`,
    industryBenchmarks: [
      'Numeric AI Flux Analysis is the AI-native lead',
      'FloQast rolling AI flux',
      'Best-in-class flux cycle <1 day',
    ],
    whyItMatters: `AI-generated initial flux commentary is the obvious play. We already have AP/AR data context — generating "AP increased 18% because invoice volume from PackRight rose 40% this month after their contract renewal" is straightforward when the system already knows the AP transaction story.`,
  },

  R2R_5: {
    whatItIs: `Combining the financials of multiple entities into a single set of group financial statements. Translate to group reporting currency, eliminate intercompany, calculate minority interest, multi-GAAP adjustments. **Out of our V1 R2R scope** — heavy and segment-specific.`,
    detailedSteps: [
      'Each entity\'s trial balance imported',
      'FX translation — closing rate for BS, average for P&L, historical for equity',
      'Intercompany matching — eliminate matched balances on both sides',
      'Minority interest calculated for partially-owned subs',
      'Multi-GAAP adjustments (Local GAAP → IFRS / US GAAP)',
      'Consolidated financial statements generated',
      'Audit-ready evidence trail',
    ],
    dataInputs: [
      'Per-entity TBs',
      'FX rates (closing, average, historical)',
      'Ownership / minority interest',
      'GAAP adjustment rules',
      'Intercompany positions',
    ],
    dataOutputs: [
      'Consolidated P&L, BS, CF',
      'Audit trail of eliminations and adjustments',
    ],
    systemsTouched: [
      'Consolidation engine (OneStream, BlackLine, Workiva, SAP BPC, Oracle FCCS)',
      'ERP per entity',
    ],
    commonPainPoints: [
      'Lives in massive Excel models that one person owns',
      'Intercompany doesn\'t match',
      'FX rates pulled manually, applied inconsistently',
      'Top-side adjustments break entity-TB-to-consol-TB tie',
      'Auditors find issues here',
    ],
    whatGoodLooksLike: `Auto-import entity TBs. Auto-match intercompany. FX rates pulled from a single source. Audit-ready evidence trail. Multi-GAAP rule engine.`,
    industryBenchmarks: [
      'OneStream is the unified close + consolidation leader',
      'SAP S/4 Group Reporting / Oracle FCCS — ERP-native',
      'BlackLine, Workiva — point solutions',
    ],
    whyItMatters: `**Out of V1 scope per Risk #4.** Heavy and segment-specific. Ship the close orchestration + JE + recs MVP first. Consolidation is a year-2+ build or a partner-integration.`,
  },

  R2R_6: {
    whatItIs: `Turning closed numbers into formal filings — P&L, BS, CF, notes for statutory filing; GST/VAT returns, TDS, withholding, country-specific (MCA, IRAS, LHDN, BIR). Per-jurisdiction work; partner where complexity warrants.`,
    detailedSteps: [
      'Map GL data to statutory disclosures per jurisdiction',
      'Generate statutory P&L, BS, CF in required format',
      'File tax returns (GST/VAT/SST/TDS) with authority',
      'XBRL/iXBRL tagging for SEC / regulatory filing',
      'SOX controls evidence for US-listed',
      'Notes to financial statements',
      'Audit support package',
    ],
    dataInputs: [
      'Closed financials',
      'Per-jurisdiction filing rules',
      'Tax data',
      'XBRL taxonomies',
    ],
    dataOutputs: [
      'Filed statutory financial statements',
      'Filed tax returns',
      'XBRL/iXBRL packages',
      'SOX evidence',
    ],
    systemsTouched: [
      'Workiva, Sovos, Avalara, ClearTax, Thomson Reuters ONESOURCE',
      'Tax authority portals',
    ],
    commonPainPoints: [
      'Per-jurisdiction work — tax rules change quarterly',
      'Statutory and management reporting use different data sets, don\'t reconcile',
      'XBRL tagging painful and error-prone',
      'Late changes to close don\'t propagate to filings',
    ],
    whatGoodLooksLike: `Auto-generation of statutory financials with one-click filing. Tax returns auto-prepared from GL. XBRL tagging automated. Single source of truth across statutory + management reporting.`,
    industryBenchmarks: [
      'Workiva for SEC + SOX',
      'Sovos / Avalara for global tax',
      'ClearTax for India + expanding SEA',
    ],
    whyItMatters: `**Phase 3 P1.** Partner with ClearTax / Sovos / Avalara where complexity warrants; build native where regulation aligns with our localization moat (MyInvois, InvoiceNow, e-Faktur).`,
  },

  R2R_7: {
    whatItIs: `Executive summary, KPI dashboards, variance commentary, forward-looking commentary delivered to board, executive team, and department heads. The artifact stakeholders actually consume from R2R.`,
    detailedSteps: [
      'Define KPI set per audience (board, exec, department)',
      'Auto-aggregate from closed financials + operational data',
      'Variance commentary attached per KPI',
      'Forward-looking guidance written by FP&A',
      'Board pack assembled with charts, tables, commentary',
      'Department-head dashboards distributed for cost-center P&Ls',
      'Self-service drill-down for executives',
    ],
    dataInputs: [
      'Closed financials',
      'KPI definitions',
      'Variance commentary',
      'FP&A guidance',
      'Operational data (sales, headcount, etc.)',
    ],
    dataOutputs: [
      'Board pack PDF/deck',
      'Executive dashboards',
      'Department-head P&Ls',
    ],
    systemsTouched: [
      'OneStream, Workiva, Anaplan',
      'BI tools (Tableau, Power BI, Looker)',
      'Datarails / Mosaic / Cube (mid-market FP&A)',
    ],
    commonPainPoints: [
      'Board packs assembled in PowerPoint by hand, charts copy-pasted from Excel',
      'Numbers don\'t match between slides',
      'Commentary written from memory not structured analysis',
      'Last-minute changes don\'t propagate to all reports',
    ],
    whatGoodLooksLike: `Auto-generated board packs with single-source-of-truth data. Self-service drill-down. Variance commentary AI-drafted from flux analysis. Mobile-readable executive dashboards.`,
    industryBenchmarks: [
      'OneStream, Workiva for enterprise',
      'Datarails, Mosaic, Cube for mid-market FP&A',
      'Anaplan for planning + reporting unified',
    ],
    whyItMatters: `Phase 3 P1 — natural expansion once close + recs + flux are live. Mid-market FP&A space (Datarails / Mosaic / Cube) is competitive but adjacent — partner-friendly territory.`,
  },

  R2R_8: {
    whatItIs: `Match intercompany invoices and balances across entities. Settle intercompany positions. Eliminate on consolidation. Cross-entity audit trail is exactly what our entity-scoped workflow engine is designed for.`,
    detailedSteps: [
      'Identify all intercompany transactions per period',
      'Both sides reconciled — sender posted matches receiver posted',
      'Discrepancies flagged for resolution (FX, fees, timing differences)',
      'Net positions calculated per entity-pair',
      'Intercompany settlement scheduled (transfer pricing, cash settlements)',
      'Eliminations posted on consolidation',
    ],
    dataInputs: [
      'Per-entity intercompany sub-ledgers',
      'FX rates',
      'Transfer pricing rules',
    ],
    dataOutputs: [
      'Matched intercompany positions',
      'Reconciling-item log',
      'Net positions per entity-pair',
      'Elimination entries',
    ],
    systemsTouched: [
      'BlackLine Intercompany Hub (acquired Rimilia)',
      'Trintech Cadency Intercompany',
      'OneStream',
      'SAP S/4 Intercompany Matching',
    ],
    commonPainPoints: [
      'Intercompany doesn\'t match — one side booked, other didn\'t',
      'FX differences create unexplained reconciling items',
      'Transfer pricing manual',
      'Audit findings concentrate here',
    ],
    whatGoodLooksLike: `Real-time intercompany matching as transactions post. FX differences auto-explained. Transfer pricing rule-driven. Settlement schedule auto-generated.`,
    industryBenchmarks: [
      'BlackLine Intercompany Hub is the leader',
      'Trintech Cadency Intercompany',
    ],
    whyItMatters: `**P0 differentiator at the SEA multi-entity buyer.** Cross-entity audit trail is exactly what our entity-scoped workflow engine enables. Customers with India HQ + Singapore + Malaysia + Indonesia subs feel this pain monthly. Architecting for this from day one is structural moat.`,
  },
};
